import lantern from '@/assets/craft-lantern.jpg';
import piggy from '@/assets/craft-piggy.jpg';
import tohe from '@/assets/craft-tohe.jpg';

export type Station = {
  id: string; number: string; name: string; theme: string; category: string; location: string;
  image: string; duration: string; price: number; rating: string; artisan: string;
  teaser: string; story: string; lockedStory: string; challenge: string; steps: { title: string; description: string }[];
};
export const stations: Station[] = [
  { id: 'phu-binh', number: '01', name: 'Phú Bình Lantern Village', theme: 'LIGHT', category: 'Craft Villages', location: 'Hồ Chí Minh City', image: lantern, duration: '2 hours', price: 320000, rating: '4.9', artisan: 'The lantern makers of Phú Bình', teaser: 'Memories of light beneath the full moon.', story: 'Long before the streets glowed with electric light, a lantern was enough to turn an evening into a celebration. In Phú Bình, skilled hands still bend bamboo into delicate frames and stretch vibrant paper across them. The craft carries the anticipation of a childhood Mid-Autumn Festival: the rustle of paper, the warmth of a candle, and the joy of walking beneath the moon.', lockedStory: 'In the quiet of the workshop, each artisan has a story that no photograph can quite capture. Come closer, follow the lantern trail, and discover the chapter waiting at the village.', challenge: 'Search for the Old Light', steps: [{ title: 'Locate the Alley', description: "Follow the clues to locate the artisan's home." }, { title: 'Decode the Hanging Rack', description: 'Find the lantern marked with a five-pointed star and the shortest red ribbon.' }, { title: 'Retrieve the Lantern', description: 'Use the bamboo pole to carefully retrieve the lantern you discovered.' }] },
  { id: 'tan-khanh', number: '02', name: 'Tân Khánh Piggy Bank Village · Nguyễn Văn Nhàn Workshop', theme: 'EARTH', category: 'Craft Villages', location: 'Bình Dương', image: piggy, duration: '2.5 hours', price: 280000, rating: '4.8', artisan: 'Nguyễn Văn Nhàn, a Tân Khánh clay artisan', teaser: 'Follow the clatter of clay and bring a childhood color back to life.', story: 'At the Tân Khánh piggy bank workshop, the familiar clay pig becomes a small canvas for memory. In the 30-year-old craft space of artisan Nguyễn Văn Nhàn, the clatter of molds and hand tools leads visitors to a worktable where unfinished piggy banks wait for their final details. The experience ends with a personal touch: choosing a color and painting a tiny story onto a keepsake.', lockedStory: 'The missing color is waiting somewhere in the workshop. Listen closely, search the shelves, and ask the artisan before you add the final mark to your chosen piggy bank.', challenge: 'Search for a Piece of Childhood Color', steps: [{ title: 'Follow the Sound', description: 'Follow the clatter of molds and hand tools through the 30-year-old workshop until you reach the artisan\'s worktable.' }, { title: 'Decode the Missing Piece', description: 'Find the special clay piggy bank described by the app, such as the limited-edition pig holding a gold bar or the pig on the innermost corner shelf.' }, { title: 'Receive & Add Color', description: 'Ask the artisan for a brush, choose your color, and paint the missing detail on your clay piggy bank.' }] },
  { id: 'to-he', number: '03', name: 'Tò He Clay · Making Point & Street Vendor Basket', theme: 'FLOUR', category: 'Cultural Experiences', location: 'QL1A', image: tohe, duration: '1.5 hours', price: 240000, rating: '4.9', artisan: 'The tò he makers', teaser: 'Follow the scent of rice flour to a pocket-sized folk character.', story: 'Tò he turns rice flour, glutinous rice flour, and natural colors into tiny characters that carry the warmth of Vietnamese folk play. At the making point and street-vendor display along QL1A, visitors follow the scent of fresh dough to a basket of figures, then learn how a twist, pinch, and careful touch can bring a character to life.', lockedStory: 'A hidden character is tucked among the handmade figures. Look closely, listen to the artisan\'s story, and shape one small detail with your own hands before taking the memory home.', challenge: 'Search for the Colors of Rice Flour', steps: [{ title: 'Find the Street Basket', description: 'Follow the scent of rice flour and glutinous rice flour to the tò he display and traditional craft corner along QL1A.' }, { title: 'Find the Hidden Character', description: 'Find the exact tò he character requested by the app, such as Sun Wukong holding the Ruyi Jingu Bang hidden among the figures in the bamboo basket.' }, { title: 'Touch the Dough', description: 'With the artisan\'s guidance, knead and shape one small detail, or receive the found figure as a keepsake.' }] },
];
export const money = (value: number) => new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(value);
export type Booking = { id: string; stationId: string; date: string; time: string; participants: number };
export type Journey = { bookings: Booking[]; unlocked: string[]; completed: string[]; reviews: { stationId: string; rating: number; text: string }[] };
export const initialJourney: Journey = { bookings: [], unlocked: [], completed: [], reviews: [] };
const key = 'phieu-viet-journey-v1';
export function loadJourney(): Journey {
  if (typeof window === 'undefined') return initialJourney;
  try { const value = JSON.parse(localStorage.getItem(key) || '{}'); return { ...initialJourney, ...value }; }
  catch { return initialJourney; }
}
export function saveJourney(value: Journey) { if (typeof window !== 'undefined') localStorage.setItem(key, JSON.stringify(value)); }
export function getStation(id: string) { return stations.find(s => s.id === id); }
