import { createFileRoute, Link } from '@tanstack/react-router';
import { useState } from 'react';
import { ArrowRight, Check, Gift, LockKeyhole } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useJourney } from '@/components/site/JourneyContext';
import { getStation } from '@/lib/journey';
import { pageHead } from '@/lib/meta';
export const Route=createFileRoute('/challenge/$stationId')({head:()=>pageHead('Station challenge','Follow the clues, meet the artisan, and create a new memory.'),component:Challenge});
function Challenge(){const {stationId}=Route.useParams();const s=getStation(stationId);const {journey}=useJourney();const [step,setStep]=useState(0);if(!s)return <main className="section-wrap py-24">Station not found.</main>;if(!journey.unlocked.includes(s.id))return <main className="section-wrap py-24 text-center"><LockKeyhole className="mx-auto text-primary"/><h1 className="mt-4 font-display text-3xl">Unlock this story first</h1><Button asChild className="mt-6"><Link to="/unlock/$stationId" params={{stationId:s.id}}>Go to unlock</Link></Button></main>;return <main className="section-wrap max-w-3xl py-16 sm:py-24"><p className="eyebrow">Station {s.number} / {s.theme}</p><h1 className="mt-4 font-display text-5xl">{s.challenge}</h1><p className="mt-5 text-muted-foreground">{s.name} · A three-part real-world activity</p><div className="mt-10 flex gap-2">{s.steps.map((_,i)=><div key={i} className={`h-1.5 flex-1 ${i<=step?'bg-primary':'bg-border'}`}/>)}</div><div className="mt-10 border border-gold bg-card p-8 sm:p-12"><p className="eyebrow">Step {Math.min(step+1,3)} of 3</p><h2 className="mt-5 font-display text-3xl">{s.steps[Math.min(step,2)].title}</h2><p className="mt-4 text-lg leading-8 text-muted-foreground">{s.steps[Math.min(step,2)].description}</p><div className="mt-10 flex flex-wrap gap-3">{step<3?<Button onClick={()=>setStep(step+1)}>{step===2?'Mark activity complete':'Continue to next clue'} {step===2?<Check/>:<ArrowRight/>}</Button>:<><p className="w-full flex items-center gap-2 font-semibold text-primary"><Gift size={20}/> Activity complete · Memory Gift</p><Button asChild><Link to="/quiz/$stationId" params={{stationId:s.id}}>Share this memory <ArrowRight/></Link></Button></>}{step>0&&step<3&&<Button variant="outline" onClick={()=>setStep(step-1)}>Previous step</Button>}</div></div></main>}
