import { createFileRoute } from '@tanstack/react-router';
import { useState } from 'react';
import { Search, SlidersHorizontal } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { StationCard } from '@/components/site/StationCard';
import { stations } from '@/lib/journey';
import { pageHead } from '@/lib/meta';
export const Route = createFileRoute('/discover')({ head: () => pageHead('Discover Vietnamese heritage', 'Explore craft villages and authentic cultural experiences across Vietnam.'), component: Discover });
function Discover() { const [search,setSearch]=useState(''); const [category,setCategory]=useState('All'); const [duration,setDuration]=useState('Any duration'); const [sort,setSort]=useState('Featured'); const categories=['All','Craft Villages','Historical Sites','Museums','Cultural Experiences'];
let items=stations.filter(s => (category==='All'||s.category===category) && `${s.name} ${s.location} ${s.artisan}`.toLowerCase().includes(search.toLowerCase()) && (duration==='Any duration'||(duration==='Under 2 hours' ? parseFloat(s.duration)<2 : parseFloat(s.duration)>=2))); if(sort==='Price: low to high') items=[...items].sort((a,b)=>a.price-b.price); if(sort==='Price: high to low') items=[...items].sort((a,b)=>b.price-a.price);
return <main className="pb-24"><div className="bg-secondary py-16 sm:py-20"><div className="section-wrap"><p className="eyebrow">Places with a story</p><h1 className="mt-4 font-display text-5xl sm:text-6xl">Discover Vietnamese Heritage</h1><p className="mt-5 max-w-2xl leading-8 text-muted-foreground">Step into the workshops and traditions where memories are still being made.</p><div className="relative mt-9 max-w-2xl"><Search className="absolute left-5 top-1/2 -translate-y-1/2 text-primary" size={20}/><input aria-label="Search destinations" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search destinations, artisans, villages..." className="h-14 w-full border border-border bg-card pl-14 pr-4 outline-none focus:border-primary"/></div></div></div><div className="section-wrap pt-9"><div className="flex flex-wrap gap-2">{categories.map(c=><Button key={c} variant={category===c?'default':'outline'} onClick={()=>setCategory(c)}>{c}</Button>)}</div><div className="mt-9 flex flex-wrap items-center justify-between gap-4 border-y border-border py-5"><span className="text-sm text-muted-foreground">{items.length} experiences to explore</span><div className="flex flex-wrap items-center gap-3 text-sm"><SlidersHorizontal size={16} className="text-primary"/><select aria-label="Filter by duration" value={duration} onChange={e=>setDuration(e.target.value)} className="bg-transparent outline-none"><option>Any duration</option><option>Under 2 hours</option><option>2 hours or more</option></select><select aria-label="Sort experiences" value={sort} onChange={e=>setSort(e.target.value)} className="bg-transparent outline-none"><option>Featured</option><option>Price: low to high</option><option>Price: high to low</option></select></div></div>{items.length ? <div className="mt-8 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{items.map(s=><StationCard key={s.id} station={s}/>)}</div>:<div className="py-24 text-center"><Search size={32} className="mx-auto text-gold"/><h2 className="mt-4 font-display text-2xl">No experiences found</h2><p className="mt-2 text-muted-foreground">Try a different search or filter.</p><Button className="mt-5" onClick={()=>{setSearch('');setCategory('All');setDuration('Any duration')}}>Clear filters</Button></div>}</div></main> }
