import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowRight, Clock3, Headphones, LockKeyhole, MapPin, Pause, Play, Volume2 } from 'lucide-react';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { useJourney } from '@/components/site/JourneyContext';
import { getStation, money } from '@/lib/journey';
import { pageHead } from '@/lib/meta';
export const Route = createFileRoute('/stories/$stationId')({ head: ({ params }) => pageHead(getStation(params.stationId)?.name || 'Story', 'Discover the people and traditions behind a Vietnamese cultural experience.'), component: Story });
function Story(){const {stationId}=Route.useParams(); const s=getStation(stationId); const {journey}=useJourney(); const [playing,setPlaying]=useState(false); const [progress,setProgress]=useState(0); if(!s) return <main className="section-wrap py-24"><h1>Story not found</h1><Link to="/discover">Back to discover</Link></main>; const unlocked=journey.unlocked.includes(s.id);
return <main><div className="relative h-[440px] bg-deep sm:h-[540px]"><img src={s.image} alt={s.name} width={1008} height={752} className="h-full w-full object-cover"/><div className="dark-shade absolute inset-0"/><div className="section-wrap absolute inset-x-0 bottom-12 text-primary-foreground"><p className="text-xs font-bold uppercase tracking-[.2em] text-gold">Chapter {s.number} · {s.theme}</p><h1 className="mt-3 max-w-3xl font-display text-5xl sm:text-6xl">{s.name}</h1><div className="mt-5 flex flex-wrap gap-5 text-sm"><span className="flex items-center gap-2"><MapPin size={16}/>{s.location}</span><span className="flex items-center gap-2"><Clock3 size={16}/>{s.duration}</span></div></div></div>
<div className="section-wrap grid gap-14 py-16 lg:grid-cols-[1fr_340px] lg:gap-24"><article><p className="eyebrow">The story begins</p><h2 className="mt-4 font-display text-4xl">A memory made by hand.</h2><p className="mt-8 font-display text-xl leading-9 text-foreground">{s.story}</p><div className="relative mt-7 overflow-hidden border-t border-gold pt-7">{unlocked ? <><p className="text-lg leading-9 text-muted-foreground">{s.lockedStory}</p><p className="mt-6 text-sm font-semibold text-primary">Story unlocked in your journey.</p></> : <><p aria-hidden="true" className="select-none blur-[6px] text-lg leading-9 text-muted-foreground">{s.lockedStory}</p><div className="absolute inset-x-0 bottom-0 flex flex-col items-center justify-end bg-gradient-to-t from-background via-background/90 to-transparent pt-20 text-center"><LockKeyhole className="text-primary" size={25}/><h3 className="mt-4 font-display text-2xl">The next chapter is waiting for you here.</h3><p className="mt-2 max-w-sm text-sm leading-7 text-muted-foreground">Visit the destination, scan the QR code, and unlock the rest of the story.</p></div></>}</div><div className="mt-10 flex flex-wrap gap-3"><Button asChild size="lg"><Link to="/book/$stationId" params={{stationId:s.id}}>Book This Experience <ArrowRight/></Link></Button><Button asChild variant="editorial" size="lg"><a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(s.name + ' ' + s.location)}`} target="_blank" rel="noreferrer">View Location <MapPin/></a></Button></div>
<div className="mt-16 border-t border-border pt-9"><div className="flex items-center gap-3"><Headphones className="text-primary"/><div><h3 className="font-display text-2xl">Audio guide</h3><p className="text-xs text-muted-foreground">Station {s.number} · Preview narration</p></div></div><div className="mt-5 flex items-center gap-4 border border-border bg-card p-4"><Button size="icon" aria-label={playing?'Pause audio preview':'Play audio preview'} onClick={()=>{setPlaying(!playing);if(progress===0)setProgress(10)}}>{playing?<Pause/>:<Play/>}</Button><input aria-label="Audio preview position" type="range" min="0" max="200" value={progress} onChange={e=>setProgress(Number(e.target.value))} className="min-w-0 flex-1 accent-primary"/><span className="text-xs tabular-nums text-muted-foreground">{`0${Math.floor(progress/60)}:${String(progress%60).padStart(2,'0')}`} / 03:20</span><Volume2 size={17} className="text-primary"/></div><p className="mt-2 text-xs text-muted-foreground">Audio recording coming soon; preview controls only.</p></div></article>
<aside><div className="sticky top-28 border border-gold bg-card p-7"><p className="eyebrow">At a glance</p><h3 className="mt-3 font-display text-2xl">Make this memory yours</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">Meet {s.artisan.toLowerCase()} and try the craft yourself.</p><div className="my-6 space-y-3 border-y border-border py-5 text-sm"><div className="flex justify-between"><span>Experience</span><strong>{s.duration}</strong></div><div className="flex justify-between"><span>Location</span><strong>{s.location}</strong></div><div className="flex justify-between"><span>From</span><strong>{money(s.price)}</strong></div></div><Button asChild className="w-full"><Link to="/book/$stationId" params={{stationId:s.id}}>Reserve your place <ArrowRight/></Link></Button></div></aside></div></main>}
