import { createFileRoute, Link } from '@tanstack/react-router';
import { useState } from 'react';
import { ArrowRight, CheckCircle2, MapPin, QrCode, ScanLine } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useJourney } from '@/components/site/JourneyContext';
import { getStation } from '@/lib/journey';
import { pageHead } from '@/lib/meta';
export const Route=createFileRoute('/unlock/$stationId')({head:()=>pageHead('Unlock your story','Explore the simulated QR and location verification journey.'),component:Unlock});
function Unlock(){const {stationId}=Route.useParams();const s=getStation(stationId);const {journey,update}=useJourney();const [phase,setPhase]=useState<'ready'|'scanned'|'outside'|'verified'>('ready');if(!s)return <main className="section-wrap py-24">Station not found.</main>;const unlocked=journey.unlocked.includes(s.id);function verify(){setPhase('verified');update(j=>({...j,unlocked:j.unlocked.includes(s.id)?j.unlocked:[...j.unlocked,s.id]}))}return <main className="section-wrap max-w-3xl py-16 text-center sm:py-24"><p className="eyebrow">Station {s.number} · {s.theme}</p><h1 className="mt-4 font-display text-5xl">Unlock your story</h1><p className="mt-4 text-muted-foreground">You are exploring: <strong className="text-foreground">{s.name}</strong></p><div className="mx-auto mt-10 max-w-lg border border-gold bg-card p-8 sm:p-12"><div className="mx-auto flex aspect-square max-w-64 items-center justify-center border-2 border-dashed border-gold bg-muted"><ScanLine size={88} strokeWidth={1} className="text-primary"/></div>{phase==='ready'&&!unlocked&&<><h2 className="mt-8 font-display text-2xl">Find the next chapter</h2><p className="mt-3 text-sm leading-7 text-muted-foreground">This prototype simulates scanning a station QR code. It does not use your camera.</p><Button className="mt-6 w-full" onClick={()=>setPhase('scanned')}><QrCode/> Simulate QR Scan</Button></>}{phase==='scanned'&&<><p className="mt-7 flex items-center justify-center gap-2 text-sm text-primary"><CheckCircle2 size={18}/> QR Code Verified (simulation)</p><h2 className="mt-5 font-display text-2xl">Location verification</h2><p className="mt-3 text-sm leading-7 text-muted-foreground">Choose a simulated result to preview the on-site experience. No location access is requested.</p><div className="mt-6 flex flex-wrap justify-center gap-3"><Button onClick={verify}>Simulate at destination</Button><Button variant="outline" onClick={()=>setPhase('outside')}>Simulate outside area</Button></div></>}{phase==='outside'&&<><MapPin className="mx-auto mt-7 text-primary"/><h2 className="mt-3 font-display text-2xl">Outside the experience area</h2><p className="mt-3 text-sm text-muted-foreground">Please move closer to the destination to unlock the next chapter.</p><Button className="mt-6" onClick={()=>setPhase('scanned')}>Try verification again</Button></>}{(phase==='verified'||unlocked)&&<><CheckCircle2 className="mx-auto mt-7 text-primary" size={32}/><h2 className="mt-3 font-display text-2xl">Story unlocked</h2><p className="mt-3 text-sm text-muted-foreground">QR Code Verified · Location Confirmed · Story Unlocked</p><Button asChild className="mt-6"><Link to="/challenge/$stationId" params={{stationId:s.id}}>Begin station challenge <ArrowRight/></Link></Button></>}</div></main>}
