import { createContext, useContext, useEffect, useState, type ReactNode } from 'react';

export type Language = 'vi' | 'en';

const translations: Record<string, string> = {
  'Page not found': 'Không tìm thấy trang',
  "This page didn't load": 'Trang này chưa thể tải',
  'Something went wrong on our end. You can try refreshing or head back home.': 'Đã xảy ra lỗi ở phía chúng tôi. Bạn có thể thử tải lại trang hoặc quay về trang chủ.',
  'Try again': 'Thử lại',
  'Go home': 'Về trang chủ',
  'Search': 'Tìm kiếm',
  'Profile': 'Hồ sơ',
  'Start Your Journey': 'Bắt đầu hành trình',
  'Discover': 'Khám phá',
  'Journeys': 'Hành trình',
  'Stories': 'Câu chuyện',
  'About': 'Về Phiêu Việt',
  'Rewards': 'Phần thưởng',
  'For Partners': 'Đối tác',
  'Partner Portal': 'Cổng đối tác',
  'Become a Partner': 'Trở thành đối tác',
  'Support': 'Hỗ trợ',
  'Contact': 'Liên hệ',
  'Help Center': 'Trung tâm trợ giúp',
  'A journey through Vietnamese heritage': 'Hành trình qua di sản Việt Nam',
  'Fragments of childhood': 'Mảnh ghép tuổi thơ',
  'Explore the Stories': 'Khám phá câu chuyện',
  'The story behind the journey': 'Câu chuyện phía sau hành trình',
  'Some memories are meant to be lived again.': 'Có những ký ức cần được sống lại.',
  'Our story': 'Câu chuyện của chúng tôi',
  'One journey · Three memories': 'Một hành trình · Ba ký ức',
  'Light. Earth. Flour.': 'Ánh sáng. Đất. Bột gạo.',
  'Follow the threads of childhood through three living traditions.': 'Theo những mạch ký ức tuổi thơ qua ba truyền thống sống động.',
  'See the journey': 'Xem hành trình',
  'Curated for the curious': 'Trải nghiệm được tuyển chọn',
  'Featured experiences': 'Trải nghiệm nổi bật',
  'Discover all': 'Khám phá tất cả',
  'Your story starts here': 'Câu chuyện của bạn bắt đầu từ đây',
  'The journey is yours to make.': 'Hành trình này là của bạn.',
  'A collection of moments': 'Bộ sưu tập khoảnh khắc',
  'Open your Việt Ký': 'Mở Việt Ký của bạn',
  'Made around you': 'Được tạo riêng cho bạn',
  'Not sure where to begin?': 'Chưa biết bắt đầu từ đâu?',
  'Design your journey': 'Thiết kế hành trình',
  'The hands behind the heritage': 'Những đôi tay gìn giữ di sản',
  'Meet the makers who keep stories alive.': 'Gặp những người gìn giữ câu chuyện sống mãi.',
  'Meet Phiêu Việt': 'Gặp gỡ Phiêu Việt',
  'Words from the journey': 'Lời kể từ hành trình',
  'Your next memory is waiting.': 'Ký ức tiếp theo đang chờ bạn.',
  'Begin Your Journey': 'Bắt đầu hành trình',
  'Station': 'Trạm',
  'From': 'Từ',
  'hours': 'giờ',
  'The living archive': 'Kho lưu trữ sống',
  'Stories worth finding': 'Những câu chuyện đáng tìm',
  'Three chapters. Three traditions. Each story begins here and continues where the craft lives.': 'Ba chương. Ba truyền thống. Mỗi câu chuyện bắt đầu từ đây và tiếp nối nơi nghề thủ công hiện hữu.',
  'Places with a story': 'Những nơi có câu chuyện',
  'Discover Vietnamese Heritage': 'Khám phá di sản Việt Nam',
  'Search destinations, artisans, villages...': 'Tìm kiếm điểm đến, nghệ nhân, làng nghề...',
  'All': 'Tất cả',
  'Any duration': 'Mọi thời lượng',
  'Under 2 hours': 'Dưới 2 giờ',
  'Price: low to high': 'Giá: thấp đến cao',
  'Price: high to low': 'Giá: cao đến thấp',
  'A journey made around you': 'Hành trình được tạo riêng cho bạn',
  'Tell me how you want to experience Vietnam. Are you drawn to lanterns, clay crafts, or childhood folk art?': 'Hãy cho tôi biết bạn muốn trải nghiệm Việt Nam như thế nào. Bạn yêu thích đèn lồng, đồ đất sét hay nghệ thuật dân gian tuổi thơ?',
  'Describe your trip': 'Mô tả chuyến đi',
  'Your personal journey': 'Hành trình cá nhân',
  'My bookings': 'Đặt chỗ của tôi',
  'My Việt Ký': 'Việt Ký của tôi',
  'Digital Stamps': 'Con dấu số',
  'Bookings': 'Đặt chỗ',
  'Every journey leaves a mark': 'Mỗi hành trình đều để lại dấu ấn',
  'Back to Việt Ký': 'Quay lại Việt Ký',
  'A journey to keep': 'Hành trình để lưu giữ',
  'Your memory pieces': 'Những mảnh ký ức của bạn',
  'View rewards': 'Xem phần thưởng',
  'In your own words': 'Theo lời kể của bạn',
  'You haven’t shared a review yet. Complete a station to tell its story in your own words.': 'Bạn chưa chia sẻ đánh giá. Hoàn thành một trạm để kể câu chuyện theo cách của riêng bạn.',
  'Discover a station': 'Khám phá một trạm',
  'Unlock this story first': 'Hãy mở khóa câu chuyện này trước',
  'Unlock this station first': 'Hãy mở khóa trạm này trước',
  'Go to unlock': 'Đến trang mở khóa',
  'Book This Experience': 'Đặt trải nghiệm này',
  'Reserve your place': 'Đặt chỗ của bạn',
  'Simulate QR Scan': 'Mô phỏng quét QR',
  'Audio guide': 'Hướng dẫn âm thanh',
  'At a glance': 'Tổng quan',
  'Make this memory yours': 'Biến ký ức này thành của bạn',
  'Ticket not found': 'Không tìm thấy vé',
  'Discover experiences': 'Khám phá trải nghiệm',
  'Booking ID': 'Mã đặt chỗ',
  'Experience not found.': 'Không tìm thấy trải nghiệm.',
  'Station not found.': 'Không tìm thấy trạm.',
  'Story not found': 'Không tìm thấy câu chuyện',
  'Back to discover': 'Quay lại khám phá',
  'About Phiêu Việt': 'Về Phiêu Việt',
  'A different way to find your way back.': 'Một cách khác để tìm đường trở về.',
  'Find your first story': 'Tìm câu chuyện đầu tiên',
  'Content overview · Prototype only': 'Tổng quan nội dung · Chỉ dành cho bản mẫu',
  'Phiêu Việt content': 'Nội dung Phiêu Việt',
  'View story': 'Xem câu chuyện',
  'Back to story': 'Quay lại câu chuyện',
  'A place in the story': 'Một nơi trong câu chuyện',
  'Book your experience': 'Đặt trải nghiệm của bạn',
  'Choose a date and reserve your cultural experience with Phiêu Việt.': 'Chọn ngày và đặt trải nghiệm văn hóa cùng Phiêu Việt.',
  'Date': 'Ngày',
  'Time': 'Thời gian',
  'Participants': 'Số người tham gia',
  'Remove participant': 'Xóa người tham gia',
  'Add participant': 'Thêm người tham gia',
  'Please select a date to continue.': 'Vui lòng chọn ngày để tiếp tục.',
  'This is a prototype reservation. No payment is collected and your chosen date is not confirmed with a venue.': 'Đây là đặt chỗ bản mẫu. Không có khoản thanh toán nào được thu và ngày bạn chọn chưa được xác nhận với địa điểm.',
  'Booking summary': 'Tóm tắt đặt chỗ',
  'Experience ×': 'Trải nghiệm ×',
  'Platform fee (5%)': 'Phí nền tảng (5%)',
  'Total': 'Tổng cộng',
  'Confirm Booking': 'Xác nhận đặt chỗ',
  'The story begins': 'Câu chuyện bắt đầu',
  'A memory made by hand.': 'Một ký ức được tạo nên bằng đôi tay.',
  'Story unlocked in your journey.': 'Câu chuyện đã được mở khóa trong hành trình của bạn.',
  'The next chapter is waiting for you here.': 'Chương tiếp theo đang chờ bạn tại đây.',
  'Visit the destination, scan the QR code, and unlock the rest of the story.': 'Hãy đến điểm đến, quét mã QR và mở khóa phần còn lại của câu chuyện.',
  'View Location': 'Xem vị trí',
  'Pause audio preview': 'Tạm dừng bản nghe thử',
  'Play audio preview': 'Phát bản nghe thử',
  'Audio preview position': 'Vị trí bản nghe thử',
  'Audio recording coming soon; preview controls only.': 'Bản ghi âm sẽ sớm ra mắt; các nút hiện chỉ để xem trước.',
  'Experience': 'Trải nghiệm',
  'Location': 'Địa điểm',
  'Welcome back': 'Chào mừng trở lại',
  'Your memories are right where you left them, on this device.': 'Những ký ức của bạn vẫn ở đây, trên thiết bị này.',
  'Destinations': 'Điểm đến',
  'Memory Pieces': 'Mảnh ký ức',
  'No bookings yet.': 'Chưa có đặt chỗ nào.',
  'Continue exploring': 'Tiếp tục khám phá',
  'My Rewards': 'Phần thưởng của tôi',
  'My Reviews': 'Đánh giá của tôi',
  'A memory worth keeping.': 'Một ký ức đáng lưu giữ.',
  'Your Reviews': 'Đánh giá của bạn',
  'You have collected': 'Bạn đã thu thập',
  'stamp': 'con dấu',
  'stamps': 'con dấu',
  'Cultural Journey Badge': 'Huy hiệu hành trình văn hóa',
  'Discount Voucher': 'Phiếu giảm giá',
  'Premium Cultural Souvenir': 'Quà lưu niệm văn hóa cao cấp',
  'Milestone unlocked in this prototype.': 'Cột mốc đã được mở khóa trong bản mẫu này.',
  'Collect more stamps to unlock this milestone.': 'Thu thập thêm con dấu để mở khóa cột mốc này.',
  'A lovely idea.': 'Một ý tưởng thật hay.',
  'Need inspiration?': 'Cần cảm hứng?',
  'Trip Designer · Prototype': 'Thiết kế chuyến đi · Bản mẫu',
  'I love traditional crafts...': 'Tôi yêu các nghề thủ công truyền thống...',
  'Send message': 'Gửi tin nhắn',
  'I have half a day.': 'Tôi có nửa ngày.',
  'I’m traveling with my family.': 'Tôi đi cùng gia đình.',
  'I love traditional crafts.': 'Tôi yêu nghề thủ công truyền thống.',
  'I want to discover childhood culture.': 'Tôi muốn khám phá văn hóa tuổi thơ.',
  'Your suggested itinerary': 'Lịch trình gợi ý cho bạn',
  'Stop': 'Điểm dừng',
  'Explore': 'Khám phá',
  'Suggestions are generated from local sample journeys, not a live AI service.': 'Gợi ý được tạo từ các hành trình mẫu cục bộ, không phải dịch vụ AI trực tiếp.',
  'After the experience': 'Sau trải nghiệm',
  'Memory Sharing Station': 'Trạm chia sẻ ký ức',
  'Question': 'Câu hỏi',
  'of 3': 'trên 3',
  'What did you experience?': 'Bạn đã trải nghiệm điều gì?',
  'I followed the clue.': 'Tôi đã đi theo manh mối.',
  'I talked with the artisan.': 'Tôi đã trò chuyện với nghệ nhân.',
  'I explored the station.': 'Tôi đã khám phá trạm.',
  'How did you feel?': 'Bạn cảm thấy thế nào?',
  'Rate': 'Đánh giá',
  'Tell us about your experience...': 'Hãy kể cho chúng tôi về trải nghiệm của bạn...',
  'Your experience': 'Trải nghiệm của bạn',
  'Would you come back to conquer the next station?': 'Bạn có quay lại để chinh phục trạm tiếp theo không?',
  "Definitely — I'm ready for the next station.": 'Chắc chắn rồi — tôi đã sẵn sàng cho trạm tiếp theo.',
  "I'm a little tired, but excited for the next one.": 'Tôi hơi mệt, nhưng rất háo hức với trạm tiếp theo.',
  "I'll invite friends and come back later.": 'Tôi sẽ rủ bạn bè và quay lại sau.',
  'Next question': 'Câu hỏi tiếp theo',
  'Collect memory piece': 'Thu thập mảnh ký ức',
  'Back': 'Quay lại',
  'Search for the Old Light': 'Tìm kiếm ánh sáng xưa',
  'Search for a Piece of Childhood Color': 'Tìm kiếm sắc màu tuổi thơ',
  'Search for the Colors of Rice Flour': 'Tìm kiếm sắc màu bột gạo',
  'Locate the Alley': 'Tìm con hẻm',
  'Follow the Sound': 'Đi theo âm thanh',
  'Find the Traditional Corner': 'Tìm góc truyền thống',
  'Decode the Hanging Rack': 'Giải mã giá treo',
  'Find the Missing Piece': 'Tìm mảnh ghép còn thiếu',
  'Find the Hidden Character': 'Tìm nhân vật ẩn',
  'Retrieve the Lantern': 'Lấy chiếc đèn lồng',
  'Receive & Decorate': 'Nhận và trang trí',
  'Touch the Flour': 'Chạm vào bột',
  'Phú Bình Lantern Village': 'Làng đèn lồng Phú Bình',
  'Tân Khánh Piggy Bank Village': 'Làng heo đất Tân Khánh',
  'CLAY Tò He': 'Tò he đất nặn',
  'Memories of light beneath the full moon.': 'Ký ức ánh sáng dưới trăng rằm.',
  'The sound of clay and childhood savings.': 'Âm thanh của đất và những khoản tiết kiệm tuổi thơ.',
  'The first toys shaped from flour and natural colors.': 'Những món đồ chơi đầu tiên được nặn từ bột và màu tự nhiên.',
  '2 hours': '2 giờ',
  '2.5 hours': '2,5 giờ',
  '1.5 hours': '1,5 giờ',
  'Hồ Chí Minh City': 'Thành phố Hồ Chí Minh',
  'The lantern makers of Phú Bình': 'Những người làm đèn lồng Phú Bình',
  'The clay artisans of Tân Khánh': 'Những nghệ nhân đất sét Tân Khánh',
  'The tò he makers': 'Những người làm tò he',
  'The page you\'re looking for doesn\'t exist or has been moved.': 'Trang bạn tìm không tồn tại hoặc đã được chuyển đi.',
  'Phiêu Việt home': 'Trang chủ Phiêu Việt',
  'Main navigation': 'Điều hướng chính',
  'Switch to English': 'Chuyển sang tiếng Anh',
  'Close menu': 'Đóng menu',
  'Open menu': 'Mở menu',
  'Mobile navigation': 'Điều hướng di động',
  'Rediscover memories in the places where they were made.': 'Tìm lại ký ức tại chính nơi chúng được tạo nên.',
  'Crafted for the stories that stay with us.': 'Dành cho những câu chuyện còn mãi.',
  'Lantern craft village': 'Làng nghề đèn lồng',
  'Our reason for wandering': 'Lý do chúng ta lên đường',
  'The stories we keep are the stories we live.': 'Những câu chuyện ta gìn giữ là những câu chuyện ta sống cùng.',
  'Phiêu Việt is a cultural journey through the places, people, and crafts that shaped Vietnamese childhood. We believe heritage feels closest when you meet the hands keeping it alive.': 'Phiêu Việt là hành trình văn hóa qua những nơi chốn, con người và nghề thủ công đã nuôi dưỡng tuổi thơ Việt Nam. Chúng tôi tin di sản trở nên gần gũi nhất khi bạn gặp những đôi tay đang gìn giữ nó.',
  'Follow a lantern into a village workshop. Shape a keepsake from clay. Discover a tiny figure made from rice flour. Along the way, stories become experiences, and experiences become memories you can carry.': 'Theo ánh đèn vào xưởng làng nghề. Tạo một món quà từ đất sét. Khám phá hình hài nhỏ làm từ bột gạo. Trên hành trình ấy, câu chuyện trở thành trải nghiệm và trải nghiệm trở thành ký ức bạn có thể mang theo.',
  'Content overview': 'Tổng quan nội dung',
  'Prototype overview of the Phiêu Việt stories, stations, and journey activity.': 'Tổng quan bản mẫu về câu chuyện, trạm và hoạt động hành trình của Phiêu Việt.',
  'This page shows sample content and activity saved on this device. It is not a protected administration system.': 'Trang này hiển thị nội dung mẫu và hoạt động được lưu trên thiết bị. Đây không phải hệ thống quản trị được bảo vệ.',
  'Reviews': 'Đánh giá',
  'Destinations & stories': 'Điểm đến và câu chuyện',
  'Category': 'Danh mục',
  'Story': 'Câu chuyện',
  'Publishing, editing, uploads, and access control require a connected content service and are not enabled in this prototype.': 'Xuất bản, chỉnh sửa, tải lên và kiểm soát quyền truy cập cần dịch vụ nội dung được kết nối và chưa được bật trong bản mẫu này.',
  'an experience': 'một trải nghiệm',
  'Payment is not collected in this prototype.': 'Bản mẫu này không thu tiền thanh toán.',
  'Continue to payment': 'Tiếp tục thanh toán',
  'Your booking is confirmed.': 'Đặt chỗ của bạn đã được xác nhận.',
  'Station challenge': 'Thử thách tại trạm',
  'Follow the clues, meet the artisan, and create a new memory.': 'Theo manh mối, gặp nghệ nhân và tạo nên một ký ức mới.',
  'A three-part real-world activity': 'Hoạt động thực tế gồm ba phần',
  'Step': 'Bước',
  'Mark activity complete': 'Đánh dấu hoàn thành hoạt động',
  'Continue to next clue': 'Tiếp tục đến manh mối tiếp theo',
  'Activity complete · Memory Gift': 'Hoạt động hoàn tất · Quà ký ức',
  'Share this memory': 'Chia sẻ ký ức này',
  'Previous step': 'Bước trước',
  'Challenge unavailable.': 'Thử thách không khả dụng.',
  'Design your journey': 'Thiết kế hành trình',
  'Find a cultural itinerary inspired by your time and interests.': 'Tìm lịch trình văn hóa dựa trên thời gian và sở thích của bạn.',
  'Design Your Journey': 'Thiết kế hành trình của bạn',
  'Tell us how you want to experience Vietnam. We’ll sketch a cultural route around you.': 'Hãy cho chúng tôi biết bạn muốn trải nghiệm Việt Nam như thế nào. Chúng tôi sẽ phác thảo một tuyến văn hóa dành riêng cho bạn.',
  'Explore craft villages and authentic cultural experiences across Vietnam.': 'Khám phá các làng nghề và trải nghiệm văn hóa chân thực khắp Việt Nam.',
  'Craft Villages': 'Làng nghề',
  'Historical Sites': 'Di tích lịch sử',
  'Museums': 'Bảo tàng',
  'Cultural Experiences': 'Trải nghiệm văn hóa',
  'Search destinations': 'Tìm kiếm điểm đến',
  'experiences to explore': 'trải nghiệm để khám phá',
  '2 hours or more': 'Từ 2 giờ trở lên',
  'Featured': 'Nổi bật',
  'No experiences found': 'Không tìm thấy trải nghiệm',
  'Try adjusting your search or filters.': 'Hãy thử điều chỉnh tìm kiếm hoặc bộ lọc.',
  'Cultural journeys': 'Hành trình văn hóa',
  'Rediscover memories and reconnect with authentic Vietnamese heritage through stories, craft villages, and cultural experiences.': 'Tìm lại ký ức và kết nối với di sản Việt Nam nguyên bản qua những câu chuyện, làng nghề và trải nghiệm văn hóa.',
  'Lanterns and an artisan at a Vietnamese craft village': 'Đèn lồng và nghệ nhân tại một làng nghề Việt Nam',
  '01 / 03 · Light · Earth · Flour': '01 / 03 · Ánh sáng · Đất · Bột gạo',
  'Find the places and stories that call to you.': 'Tìm những nơi chốn và câu chuyện gọi tên bạn.',
  'Read & book': 'Đọc và đặt chỗ',
  'Get to know the craft, then reserve your place.': 'Tìm hiểu nghề thủ công, rồi đặt chỗ của bạn.',
  'Visit & unlock': 'Đến thăm và mở khóa',
  'Follow the clues at the destination and reveal more.': 'Theo manh mối tại điểm đến và khám phá thêm.',
  'Keep the memory': 'Lưu giữ ký ức',
  'Collect a piece of the journey in your Việt Ký.': 'Lưu một phần hành trình vào Việt Ký của bạn.',
  'Every place leaves a little piece of itself with you.': 'Mỗi nơi chốn đều để lại một phần nhỏ trong bạn.',
  "Collect memory pieces and digital stamps as you explore. Your Việt Ký is a living record of where you've been and what you've felt.": 'Thu thập mảnh ký ức và con dấu số khi bạn khám phá. Việt Ký là ghi chép sống động về nơi bạn đã đến và điều bạn đã cảm nhận.',
  'Cultural passport · No. 001': 'Hộ chiếu văn hóa · Số 001',
  'Your cultural journey': 'Hành trình văn hóa của bạn',
  'The stories you take with you': 'Những câu chuyện bạn mang theo',
  'Tell us what you love. We’ll sketch a cultural journey just for you.': 'Hãy kể chúng tôi nghe điều bạn yêu thích. Chúng tôi sẽ phác thảo một hành trình văn hóa dành riêng cho bạn.',
  'Lantern artisan at work': 'Nghệ nhân đèn lồng đang làm việc',
  'At every stop, a local artisan welcomes you into a craft passed through generations. More than an activity, it is a chance to listen, learn, and make something worth keeping.': 'Ở mỗi điểm dừng, một nghệ nhân địa phương sẽ chào đón bạn đến với nghề thủ công truyền qua nhiều thế hệ. Hơn cả một hoạt động, đây là cơ hội để lắng nghe, học hỏi và tạo ra điều đáng lưu giữ.',
  '“The loveliest part was sitting with the maker and hearing how a simple lantern carried so many memories.”': '“Điều đáng yêu nhất là được ngồi bên người thợ và nghe cách một chiếc đèn lồng giản dị mang theo biết bao ký ức.”',
  'A journey worth remembering': 'Một hành trình đáng nhớ',
  'Your story is still unfolding': 'Câu chuyện của bạn vẫn đang tiếp diễn',
  'Step beyond the screen. Meet the people, places, crafts and stories that make Vietnamese heritage unforgettable.': 'Bước ra khỏi màn hình. Gặp gỡ những con người, nơi chốn, nghề thủ công và câu chuyện làm nên di sản Việt Nam khó quên.',
  'Light, Earth, Flour journey': 'Hành trình Ánh sáng, Đất, Bột gạo',
  'Follow a three-stop cultural journey through lanterns, clay keepsakes, and tò he.': 'Theo hành trình văn hóa ba điểm dừng qua đèn lồng, món quà đất sét và tò he.',
  'The signature journey': 'Hành trình đặc trưng',
  'Three traditional crafts. Three pieces of childhood. One journey to remember.': 'Ba nghề thủ công truyền thống. Ba mảnh ghép tuổi thơ. Một hành trình đáng nhớ.',
  'Explore story': 'Khám phá câu chuyện',
  'Begin with the story that calls to you.': 'Bắt đầu từ câu chuyện gọi tên bạn.',
  'Explore experiences': 'Khám phá trải nghiệm',
  'Partner portal': 'Cổng đối tác',
  'Prototype partner overview for visits, bookings, and experience quality.': 'Tổng quan bản mẫu dành cho đối tác về lượt thăm, đặt chỗ và chất lượng trải nghiệm.',
  'Phiêu Việt · Partner workspace': 'Phiêu Việt · Không gian đối tác',
  'Partner Dashboard': 'Bảng điều khiển đối tác',
  'Prototype figures based on bookings saved on this device; not a live partner account.': 'Số liệu bản mẫu dựa trên đặt chỗ được lưu trên thiết bị này; không phải tài khoản đối tác trực tiếp.',
  'Completed experiences': 'Trải nghiệm đã hoàn thành',
  'Gross booking value': 'Tổng giá trị đặt chỗ',
  'Verify booking': 'Xác minh đặt chỗ',
  'Enter a prototype booking ID from a digital ticket.': 'Nhập mã đặt chỗ bản mẫu từ vé điện tử.',
  'Look up': 'Tra cứu',
  'Commission': 'Hoa hồng',
  'Verify': 'Xác minh',
  'Booking verified': 'Đặt chỗ đã được xác minh',
  'No booking found for this ID.': 'Không tìm thấy đặt chỗ với mã này.',
  'Your profile': 'Hồ sơ của bạn',
  'See your bookings, stamps, and memories in one place.': 'Xem đặt chỗ, con dấu và ký ức của bạn ở một nơi.',
  'Việt Ký digital passport': 'Hộ chiếu số Việt Ký',
  'Collect memory pieces and stamps from every stop of your cultural journey.': 'Thu thập mảnh ký ức và con dấu tại mỗi điểm dừng trong hành trình văn hóa.',
  'Your cultural journey, one memory at a time.': 'Hành trình văn hóa của bạn, từng ký ức một.',
  'Destinations completed': 'Điểm đến đã hoàn thành',
  'Collected along the way': 'Thu thập trên hành trình',
  'A memory still waiting to be found.': 'Một ký ức vẫn đang chờ được tìm thấy.',
  'Digital stamp collected': 'Đã thu thập con dấu số',
  'Unlock story': 'Mở khóa câu chuyện',
  'Memory sharing station': 'Trạm chia sẻ ký ức',
  'Reflect on your cultural experience and collect a memory piece.': 'Nhìn lại trải nghiệm văn hóa và thu thập một mảnh ký ức.',
  'Your rewards': 'Phần thưởng của bạn',
  'See the cultural rewards and milestones in your Phiêu Việt journey.': 'Xem phần thưởng văn hóa và các cột mốc trong hành trình Phiêu Việt của bạn.',
  'Read the memories and ratings you shared after each experience.': 'Đọc những ký ức và đánh giá bạn đã chia sẻ sau mỗi trải nghiệm.',
  'Stories of childhood': 'Những câu chuyện tuổi thơ',
  'Read the stories behind light, earth, and flour in the living craft villages of Vietnam.': 'Đọc những câu chuyện phía sau ánh sáng, đất và bột gạo tại các làng nghề sống động của Việt Nam.',
  'Preview narration': 'Nghe thử lời kể',
  'Meet ${artisan} and try the craft yourself.': 'Gặp ${artisan} và tự mình thử nghề thủ công.',
  'Digital Memory Ticket': 'Vé Ký ức số',
  'Your Phiêu Việt cultural experience ticket and journey details.': 'Vé trải nghiệm văn hóa Phiêu Việt và thông tin hành trình của bạn.',
  'A new memory begins': 'Một ký ức mới bắt đầu',
  'Your digital memory ticket': 'Vé ký ức số của bạn',
  'Your prototype reservation has been saved on this device.': 'Đặt chỗ bản mẫu của bạn đã được lưu trên thiết bị này.',
  'Digital Experience Ticket': 'Vé trải nghiệm số',
  'Guests': 'Khách tham gia',
  'Show this ticket at the station.': 'Xuất trình vé này tại trạm.',
  'Back to your profile': 'Quay lại hồ sơ',
  'Unlock your story': 'Mở khóa câu chuyện của bạn',
  'Explore the simulated QR and location verification journey.': 'Khám phá hành trình mô phỏng quét QR và xác minh vị trí.',
  'You are exploring:': 'Bạn đang khám phá:',
  'Find the next chapter': 'Tìm chương tiếp theo',
  'This prototype simulates scanning a station QR code. It does not use your camera.': 'Bản mẫu này mô phỏng việc quét mã QR tại trạm. Ứng dụng không sử dụng camera của bạn.',
  'QR Code Verified (simulation)': 'Mã QR đã xác minh (mô phỏng)',
  'Location verification': 'Xác minh vị trí',
  'Choose a simulated result to preview the on-site experience. No location access is requested.': 'Chọn kết quả mô phỏng để xem trước trải nghiệm tại chỗ. Ứng dụng không yêu cầu quyền truy cập vị trí.',
  'Simulate at destination': 'Mô phỏng tại điểm đến',
  'Simulate outside area': 'Mô phỏng ngoài khu vực',
  'Location verified': 'Vị trí đã được xác minh',
  'Your story is now unlocked.': 'Câu chuyện của bạn đã được mở khóa.',
  'Continue to story': 'Tiếp tục đến câu chuyện',
  'Already unlocked': 'Đã mở khóa',
  'LIGHT': 'ÁNH SÁNG',
  'EARTH': 'ĐẤT',
  'FLOUR': 'BỘT GẠO',
  'Follow the clues to locate the artisan\'s home.': 'Theo manh mối để tìm nhà của nghệ nhân.',
  'Find the lantern marked with a five-pointed star and the shortest red ribbon.': 'Tìm chiếc đèn lồng có ngôi sao năm cánh và dải ruy băng đỏ ngắn nhất.',
  'Use the bamboo pole to carefully retrieve the lantern you discovered.': 'Dùng sào tre để cẩn thận lấy chiếc đèn lồng bạn đã tìm thấy.',
  'Long before the streets glowed with electric light, a lantern was enough to turn an evening into a celebration. In Phú Bình, skilled hands still bend bamboo into delicate frames and stretch vibrant paper across them. The craft carries the anticipation of a childhood Mid-Autumn Festival: the rustle of paper, the warmth of a candle, and the joy of walking beneath the moon.': 'Từ rất lâu trước khi đường phố rực sáng bởi đèn điện, một chiếc đèn lồng đã đủ biến buổi tối thành lễ hội. Ở Phú Bình, những đôi tay khéo léo vẫn uốn tre thành khung mảnh và căng giấy rực rỡ lên đó. Nghề thủ công mang theo niềm mong đợi của Tết Trung thu tuổi thơ: tiếng giấy xào xạc, hơi ấm ngọn nến và niềm vui bước đi dưới ánh trăng.',
  'In the quiet of the workshop, each artisan has a story that no photograph can quite capture. Come closer, follow the lantern trail, and discover the chapter waiting at the village.': 'Trong sự tĩnh lặng của xưởng nghề, mỗi nghệ nhân đều có một câu chuyện mà không bức ảnh nào có thể ghi lại trọn vẹn. Hãy đến gần hơn, theo dấu đèn lồng và khám phá chương chuyện đang chờ ở ngôi làng.',
  'A small clay piggy bank once held a world of possibilities. At Tân Khánh, artisans shape earth into the familiar childhood companion, then add color and character by hand. Every piece begins as a lump of clay and ends as a vessel for hopes, plans, and little treasures.': 'Một chú heo đất nhỏ từng chứa cả thế giới của những khả năng. Ở Tân Khánh, nghệ nhân tạo hình đất thành người bạn tuổi thơ quen thuộc rồi thêm màu sắc và cá tính bằng đôi tay. Mỗi sản phẩm bắt đầu từ một cục đất và kết thúc như nơi chứa những hy vọng, dự định và kho báu nhỏ.',
  'There is more to this craft than meets the eye. Listen for the workshop sounds and find the piece that tells your own story.': 'Nghề này có nhiều điều hơn những gì mắt thấy. Hãy lắng nghe âm thanh xưởng nghề và tìm món đồ kể câu chuyện của riêng bạn.',
  'Let the sounds of traditional craftsmanship guide you through the workshop.': 'Để âm thanh của nghề thủ công truyền thống dẫn lối bạn qua xưởng nghề.',
  'Find the limited-edition clay piggy bank holding a gold bar.': 'Tìm chú heo đất phiên bản giới hạn đang giữ một thỏi vàng.',
  'Decorate your own little keepsake alongside an artisan.': 'Trang trí món quà nhỏ của riêng bạn bên cạnh nghệ nhân.',
  'Before a toy came from a box, it could come from a pair of hands. Tò he figures made from rice flour and natural colors bring folk tales and childhood imaginings to life. A little twist, a careful pinch, and a playful character appears.': 'Trước khi đồ chơi bước ra từ chiếc hộp, nó có thể được tạo nên từ đôi tay. Những hình tò he làm từ bột gạo và màu tự nhiên đưa truyện dân gian cùng trí tưởng tượng tuổi thơ vào đời sống. Một vòng xoay nhỏ, một cái nắn khéo léo và nhân vật tinh nghịch xuất hiện.',
  'The most memorable part is not choosing a figure. It is learning to shape one for yourself beside the hands that have kept this tradition alive.': 'Điều đáng nhớ nhất không phải là chọn một hình tò he. Đó là học cách tự nặn một hình bên cạnh những đôi tay đã gìn giữ truyền thống này.',
  'Find the corner where the artisan shapes the first figures of the day.': 'Tìm góc nơi nghệ nhân tạo hình những nhân vật đầu tiên trong ngày.',
  'Find Sun Wukong holding the Ruyi Jingu Bang.': 'Tìm Tôn Ngộ Không đang cầm Như Ý Kim Cô Bổng.',
  'Learn from the artisan, create a small detail, and keep your creation.': 'Học từ nghệ nhân, tạo một chi tiết nhỏ và giữ lại sản phẩm của bạn.',
  'Memories of light beneath the full moon.': 'Ký ức ánh sáng dưới trăng rằm.',
  'The sound of clay and childhood savings.': 'Âm thanh của đất và những khoản tiết kiệm tuổi thơ.',
  'The first toys shaped from flour and natural colors.': 'Những món đồ chơi đầu tiên được nặn từ bột và màu tự nhiên.',
  'Station ${number} · ${theme}': 'Trạm ${number} · ${theme}',
  'From ${formatted price}': 'Từ ${formatted price}',
  'A lantern glowing in the night. The first coins in a clay piggy bank. A tiny figure shaped by hand. Phiêu Việt takes you beyond the screen and into the workshops, stories, and people keeping childhood traditions alive.': 'Một chiếc đèn lồng tỏa sáng trong đêm. Những đồng tiền đầu tiên trong chú heo đất. Một hình hài nhỏ được nặn bằng tay. Phiêu Việt đưa bạn vượt ra ngoài màn hình để bước vào những xưởng nghề, câu chuyện và con người đang gìn giữ truyền thống tuổi thơ.',
};

const reverseTranslations = Object.fromEntries(Object.entries(translations).map(([english, vietnamese]) => [vietnamese, english]));

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
};

const Context = createContext<LanguageContextValue | null>(null);
const storageKey = 'phieu-viet-language-v1';

function loadLanguage(): Language {
  if (typeof window === 'undefined') return 'vi';
  return localStorage.getItem(storageKey) === 'en' ? 'en' : 'vi';
}

function translateDocument(language: Language) {
  if (typeof document === 'undefined') return;
  const dictionary = language === 'vi' ? translations : reverseTranslations;
  const keys = Object.keys(dictionary).sort((left, right) => right.length - left.length);
  const replaceText = (value: string) => keys.reduce((text, key) => text.split(key).join(dictionary[key]), value);
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
  const textNodes: Text[] = [];
  let node = walker.nextNode();
  while (node) {
    if (node.parentElement && !['SCRIPT', 'STYLE'].includes(node.parentElement.tagName)) textNodes.push(node as Text);
    node = walker.nextNode();
  }
  textNodes.forEach((textNode) => {
    const nextText = replaceText(textNode.nodeValue || '');
    if (nextText !== textNode.nodeValue) textNode.nodeValue = nextText;
  });
  document.querySelectorAll<HTMLElement>('[aria-label], [placeholder], [title]').forEach((element) => {
    ['aria-label', 'placeholder', 'title'].forEach((attribute) => {
      const value = element.getAttribute(attribute);
      if (value) element.setAttribute(attribute, replaceText(value));
    });
  });
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('vi');

  useEffect(() => {
    const initialLanguage = loadLanguage();
    setLanguage(initialLanguage);
    document.documentElement.lang = initialLanguage;
  }, []);

  useEffect(() => {
    translateDocument(language);
    const observer = new MutationObserver(() => {
      observer.disconnect();
      translateDocument(language);
      observer.observe(document.body, { childList: true, subtree: true });
    });
    observer.observe(document.body, { childList: true, subtree: true });
    return () => observer.disconnect();
  }, [language]);

  function changeLanguage(nextLanguage: Language) {
    setLanguage(nextLanguage);
    localStorage.setItem(storageKey, nextLanguage);
    document.documentElement.lang = nextLanguage;
  }

  function toggleLanguage() {
    changeLanguage(language === 'vi' ? 'en' : 'vi');
  }

  return <Context.Provider value={{ language, setLanguage: changeLanguage, toggleLanguage }}>{children}</Context.Provider>;
}

export function useLanguage() {
  const value = useContext(Context);
  if (!value) throw new Error('LanguageProvider missing');
  return value;
}
