import { createContext, useContext, useEffect, useState, type ReactNode } from 'react';

export type Language = 'vi' | 'en';

const translations: Record<string, string> = {
  'Page not found': 'Không tìm thấy trang',
  "This page didn't load": 'Trang này chưa thể tải',
  'Something went wrong on our end. You can try refreshing or head back home.': 'Đã xảy ra lỗi ở phía chúng tôi. Bạn có thể thử tải lại trang hoặc quay về trang chủ.',
  'Try again': 'Thử lại',
  'Go home': 'Về trang chủ',
  'Search': 'Tìm kiếm',
  'Profile': 'Hồ sơ',
  'Start Your Journey': 'Bắt đầu hành trình',
  'Discover': 'Khám phá',
  'Journeys': 'Hành trình',
  'Stories': 'Câu chuyện',
  'About': 'Về Phiêu Việt',
  'Rewards': 'Phần thưởng',
  'For Partners': 'Đối tác',
  'Partner Portal': 'Cổng đối tác',
  'Become a Partner': 'Trở thành đối tác',
  'Support': 'Hỗ trợ',
  'Contact': 'Liên hệ',
  'Help Center': 'Trung tâm trợ giúp',
  'A journey through Vietnamese heritage': 'Hành trình qua di sản Việt Nam',
  'Fragments of childhood': 'Mảnh ghép tuổi thơ',
  'Explore the Stories': 'Khám phá câu chuyện',
  'The story behind the journey': 'Câu chuyện phía sau hành trình',
  'Some memories are meant to be lived again.': 'Có những ký ức cần được sống lại.',
  'Our story': 'Câu chuyện của chúng tôi',
  'One journey · Three memories': 'Một hành trình · Ba ký ức',
  'Light. Earth. Flour.': 'Ánh sáng. Đất. Bột gạo.',
  'Follow the threads of childhood through three living traditions.': 'Theo những mạch ký ức tuổi thơ qua ba truyền thống sống động.',
  'See the journey': 'Xem hành trình',
  'Curated for the curious': 'Trải nghiệm được tuyển chọn',
  'Featured experiences': 'Trải nghiệm nổi bật',
  'Discover all': 'Khám phá tất cả',
  'Your story starts here': 'Câu chuyện của bạn bắt đầu từ đây',
  'The journey is yours to make.': 'Hành trình này là của bạn.',
  'A collection of moments': 'Bộ sưu tập khoảnh khắc',
  'Open your Việt Ký': 'Mở Việt Ký của bạn',
  'Made around you': 'Được tạo riêng cho bạn',
  'Not sure where to begin?': 'Chưa biết bắt đầu từ đâu?',
  'Design your journey': 'Thiết kế hành trình',
  'The hands behind the heritage': 'Những đôi tay gìn giữ di sản',
  'Meet the makers who keep stories alive.': 'Gặp những người gìn giữ câu chuyện sống mãi.',
  'Meet Phiêu Việt': 'Gặp gỡ Phiêu Việt',
  'Words from the journey': 'Lời kể từ hành trình',
  'Your next memory is waiting.': 'Ký ức tiếp theo đang chờ bạn.',
  'Begin Your Journey': 'Bắt đầu hành trình',
  'Station': 'Trạm',
  'From': 'Từ',
  'hours': 'giờ',
  'Phu Binh Lantern Village': 'Làng lồng đèn Phú Bình',
  'Tan Khanh Piggy Bank Kiln Village': 'Xóm lò nung heo đất Tân Khánh',
  'CLAY To He Making & Street Vendor Point': 'Điểm làm & gánh Tò he CLAY',
  'Alleys around Phu Binh Parish, Lac Long Quan Street, Ward 5, District 11, Ho Chi Minh City': 'Các con hẻm nhỏ xung quanh Giáo xứ Phú Bình, đoạn đường Lạc Long Quân, Phường 5, Quận 11, TP. HCM',
  'Nguyen Van Nhan\'s 30-year-old workshop, Khanh Loi Quarter, Tan Khanh Ward': 'Xưởng làm heo đất hơn 30 năm tuổi của ông Nguyễn Văn Nhàn, tại khu phố Khánh Lợi, phường Tân Khánh',
  '2867/68/5B QL1A, Tan Thoi Nhat Ward, District 12, Ho Chi Minh City': '2867/68/5B QL1A, Phường Tân Thới Nhất, Quận 12, TP. HCM',
  'The lantern makers of Phu Binh': 'Nghệ nhân làng lồng đèn Phú Bình',
  'Nguyen Van Nhan and the Tan Khanh clay makers': 'Ông Nguyễn Văn Nhàn và các nghệ nhân đất sét Tân Khánh',
  'The CLAY to he makers': 'Nghệ nhân Tò he CLAY',
  'Unlock a memory hidden inside a red glass-paper lantern.': 'Mở khóa ký ức ẩn bên trong một chiếc lồng đèn giấy kính đỏ.',
  'Meet the makers behind a clay piggy bank shaped by three decades of memory.': 'Gặp những người làm nên chiếc heo đất từ ký ức hơn ba thập kỷ.',
  'Shape a tiny folk character and follow it into the street basket.': 'Nặn một nhân vật dân gian nhỏ và theo dấu nhân vật vào gánh hàng rong.',
  'Unlock the Lantern Museum': 'Mở khóa bảo tàng trong lòng đèn',
  'Find the Keepsake Piggy Bank': 'Tìm chiếc heo đất ký ức',
  'Find the Hidden To He Character': 'Tìm nhân vật Tò he ẩn giấu',
  'In the small alleys around Phu Binh Parish, rows of red glass-paper lanterns hang beneath the drying racks. Each one carries the glow of a childhood Mid-Autumn Festival and a one-of-a-kind memory prepared by a local family.': 'Trong những con hẻm nhỏ quanh Giáo xứ Phú Bình, những dãy lồng đèn giấy kính đỏ treo rợp dưới giàn phơi. Mỗi chiếc mang theo ánh sáng của một mùa Trung thu tuổi thơ và một món quà ký ức độc bản do người dân địa phương chuẩn bị.',
  'The lantern museum is waiting above the alley. Reach for the bamboo hook, choose one lantern at random, and discover the keepsake hidden inside.': 'Bảo tàng trong lòng đèn đang chờ trên cao. Cầm sào tre móc, chọn ngẫu nhiên một chiếc lồng đèn và khám phá món quà ký ức ẩn bên trong.',
  'At the Tan Khanh piggy bank kiln village, clay becomes a familiar vessel for childhood savings. In Mr. Nguyen Van Nhan\'s workshop, more than 30 years of molds, firing, and hand-painted details fill the space with the warm rhythm of a living craft.': 'Tại xóm lò nung heo đất Tân Khánh, đất sét trở thành chiếc hộp thân thuộc lưu giữ những đồng tiền tuổi thơ. Trong xưởng của ông Nguyễn Văn Nhàn, hơn 30 năm khuôn đúc, nung lò và vẽ tay tạo nên nhịp sống ấm áp của một nghề truyền thống.',
  'The kiln room holds the story of a craft family and the small piggy bank waiting to travel home with you. Look closely, listen to the maker, and find the marked piece.': 'Gian lò giữ câu chuyện của một gia đình làm nghề và chiếc heo đất nhỏ đang chờ theo bạn về nhà. Hãy quan sát thật kỹ, lắng nghe nghệ nhân và tìm món đồ có dấu hiệu đặc biệt.',
  'At CLAY, rice flour and natural colors become tiny figures with expressive faces and bright costumes. Visit the making point, watch the artisan\'s hands, then follow the figures into the vendor basket where Vietnamese childhood folklore comes alive.': 'Tại CLAY, bột gạo và màu tự nhiên trở thành những hình hài nhỏ với gương mặt sinh động và trang phục rực rỡ. Ghé điểm làm, xem đôi tay nghệ nhân rồi theo các nhân vật đến gánh hàng, nơi ký ức dân gian tuổi thơ Việt Nam sống dậy.',
  'One character is waiting among the handmade figures. Find the requested shape, learn the small gesture that gives it life, and bring a piece of folk play into your own story.': 'Một nhân vật đang chờ giữa những hình hài thủ công. Tìm đúng hình dáng được yêu cầu, học một động tác nhỏ để thổi hồn cho nhân vật và mang một mảnh trò chơi dân gian vào câu chuyện của bạn.',
  'Enter the Lantern Alley': 'Bước vào hẻm đèn',
  'Choose Your Lantern': 'Chọn chiếc lồng đèn của bạn',
  'Open the Memory': 'Mở món quà ký ức',
  'Follow the Kiln Trail': 'Theo dấu lò nung',
  'Spot the Mark': 'Tìm dấu hiệu đặc biệt',
  'Carry Home a Memory': 'Mang ký ức về nhà',
  'Arrive at CLAY': 'Đến CLAY',
  'Search the Vendor Basket': 'Tìm trong gánh hàng',
  'Shape One Small Detail': 'Nặn một chi tiết nhỏ',
  'Follow the lantern racks through the alleys around Phu Binh Parish on Lac Long Quan Street.': 'Theo những giàn đèn qua các con hẻm quanh Giáo xứ Phú Bình trên đoạn đường Lạc Long Quân.',
  'Use the bamboo pole and hook to select one sealed red glass-paper lantern from the hanging rack.': 'Dùng cây sào tre và móc để chọn một chiếc lồng đèn giấy kính đỏ được niêm kín trên giàn cao.',
  'Take your lantern to the artisan and discover one unique keepsake: a dried to he, a mini piggy bank, a handwritten letter, or vintage glass paper from the 1990s.': 'Mang lồng đèn đến nghệ nhân và khám phá một món quà độc bản: một con Tò he sấy khô, một chiếc heo đất mini, một lá thư tay hoặc mảnh giấy kính màu xưa từ thập niên 90.',
  'Find Mr. Nguyen Van Nhan\'s workshop in Khanh Loi Quarter and listen for the rhythm of the kiln and hand tools.': 'Tìm xưởng của ông Nguyễn Văn Nhàn tại khu phố Khánh Lợi và lắng nghe nhịp lò nung cùng tiếng dụng cụ thủ công.',
  'Find the mini piggy bank stamped with the village mark among the rows of clay forms.': 'Tìm chiếc heo đất mini có dập logo xóm nghề giữa những hàng hình hài đất sét.',
  'Choose a color, add a small detail with the artisan\'s guidance, and take your mini piggy bank home.': 'Chọn một màu, thêm một chi tiết nhỏ cùng sự hướng dẫn của nghệ nhân và mang chiếc heo đất mini về nhà.',
  'Visit the CLAY to he making point at 2867/68/5B QL1A, Tan Thoi Nhat Ward, District 12.': 'Ghé điểm làm Tò he CLAY tại 2867/68/5B QL1A, Phường Tân Thới Nhất, Quận 12.',
  'Find the exact to he character requested by the app among the handmade figures and street-vendor display.': 'Tìm đúng nhân vật Tò he được ứng dụng yêu cầu giữa những hình hài thủ công và gánh hàng.',
  'With the artisan\'s guidance, knead and shape one small detail or receive the found figure as a keepsake.': 'Dưới sự hướng dẫn của nghệ nhân, nhào nặn một chi tiết nhỏ hoặc nhận nhân vật đã tìm thấy làm kỷ niệm.',
  'The living archive': 'Kho lưu trữ sống',
  'Stories worth finding': 'Những câu chuyện đáng tìm',
  'Three chapters. Three traditions. Each story begins here and continues where the craft lives.': 'Ba chương. Ba truyền thống. Mỗi câu chuyện bắt đầu từ đây và tiếp nối nơi nghề thủ công hiện hữu.',
  'Places with a story': 'Những nơi có câu chuyện',
  'Discover Vietnamese Heritage': 'Khám phá di sản Việt Nam',
  'Search destinations, artisans, villages...': 'Tìm kiếm điểm đến, nghệ nhân, làng nghề...',
  'All': 'Tất cả',
  'Any duration': 'Mọi thời lượng',
  'Under 2 hours': 'Dưới 2 giờ',
  'Price: low to high': 'Giá: thấp đến cao',
  'Price: high to low': 'Giá: cao đến thấp',
  'A journey made around you': 'Hành trình được tạo riêng cho bạn',
  'Tell me how you want to experience Vietnam. Are you drawn to lanterns, clay crafts, or childhood folk art?': 'Hãy cho tôi biết bạn muốn trải nghiệm Việt Nam như thế nào. Bạn yêu thích đèn lồng, đồ đất sét hay nghệ thuật dân gian tuổi thơ?',
  'Describe your trip': 'Mô tả chuyến đi',
  'Your personal journey': 'Hành trình cá nhân',
  'My bookings': 'Đặt chỗ của tôi',
  'My Việt Ký': 'Việt Ký của tôi',
  'Digital Stamps': 'Con dấu số',
  'Bookings': 'Đặt chỗ',
  'Every journey leaves a mark': 'Mỗi hành trình đều để lại dấu ấn',
  'Back to Việt Ký': 'Quay lại Việt Ký',
  'A journey to keep': 'Hành trình để lưu giữ',
  'Your memory pieces': 'Những mảnh ký ức của bạn',
  'View rewards': 'Xem phần thưởng',
  'In your own words': 'Theo lời kể của bạn',
  'You haven’t shared a review yet. Complete a station to tell its story in your own words.': 'Bạn chưa chia sẻ đánh giá. Hoàn thành một trạm để kể câu chuyện theo cách của riêng bạn.',
  'Discover a station': 'Khám phá một trạm',
  'Unlock this story first': 'Hãy mở khóa câu chuyện này trước',
  'Unlock this station first': 'Hãy mở khóa trạm này trước',
  'Go to unlock': 'Đến trang mở khóa',
  'Book This Experience': 'Đặt trải nghiệm này',
  'Reserve your place': 'Đặt chỗ của bạn',
  'Simulate QR Scan': 'Mô phỏng quét QR',
  'Audio guide': 'Hướng dẫn âm thanh',
  'At a glance': 'Tổng quan',
  'Make this memory yours': 'Biến ký ức này thành của bạn',
  'Ticket not found': 'Không tìm thấy vé',
  'Discover experiences': 'Khám phá trải nghiệm',
  'Booking ID': 'Mã đặt chỗ',
  'Experience not found.': 'Không tìm thấy trải nghiệm.',
  'Station not found.': 'Không tìm thấy trạm.',
  'Story not found': 'Không tìm thấy câu chuyện',
  'Back to discover': 'Quay lại khám phá',
  'About Phiêu Việt': 'Về Phiêu Việt',
  'A different way to find your way back.': 'Một cách khác để tìm đường trở về.',
  'Find your first story': 'Tìm câu chuyện đầu tiên',
  'Content overview · Prototype only': 'Tổng quan nội dung · Chỉ dành cho bản mẫu',
  'Phiêu Việt content': 'Nội dung Phiêu Việt',
  'View story': 'Xem câu chuyện',
  'Back to story': 'Quay lại câu chuyện',
  'A place in the story': 'Một nơi trong câu chuyện',
  'Book your experience': 'Đặt trải nghiệm của bạn',
  'Choose a date and reserve your cultural experience with Phiêu Việt.': 'Chọn ngày và đặt trải nghiệm văn hóa cùng Phiêu Việt.',
  'Date': 'Ngày',
  'Time': 'Thời gian',
  'Participants': 'Số người tham gia',
  'Remove participant': 'Xóa người tham gia',
  'Add participant': 'Thêm người tham gia',
  'Please select a date to continue.': 'Vui lòng chọn ngày để tiếp tục.',
  'This is a prototype reservation. No payment is collected and your chosen date is not confirmed with a venue.': 'Đây là đặt chỗ bản mẫu. Không có khoản thanh toán nào được thu và ngày bạn chọn chưa được xác nhận với địa điểm.',
  'Booking summary': 'Tóm tắt đặt chỗ',
  'Experience ×': 'Trải nghiệm ×',
  'Total': 'Tổng cộng',
  'Confirm Booking': 'Xác nhận đặt chỗ',
  'The story begins': 'Câu chuyện bắt đầu',
  'A memory made by hand.': 'Một ký ức được tạo nên bằng đôi tay.',
  'Story unlocked in your journey.': 'Câu chuyện đã được mở khóa trong hành trình của bạn.',
  'The next chapter is waiting for you here.': 'Chương tiếp theo đang chờ bạn tại đây.',
  'Visit the destination, scan the QR code, and unlock the rest of the story.': 'Hãy đến điểm đến, quét mã QR và mở khóa phần còn lại của câu chuyện.',
  'View Location': 'Xem vị trí',
  'Pause audio preview': 'Tạm dừng bản nghe thử',
  'Play audio preview': 'Phát bản nghe thử',
  'Audio preview position': 'Vị trí bản nghe thử',
  'Audio recording coming soon; preview controls only.': 'Bản ghi âm sẽ sớm ra mắt; các nút hiện chỉ để xem trước.',
  'Experience': 'Trải nghiệm',
  'Location': 'Địa điểm',
  'Welcome back': 'Chào mừng trở lại',
  'Your memories are right where you left them, on this device.': 'Những ký ức của bạn vẫn ở đây, trên thiết bị này.',
  'Destinations': 'Điểm đến',
  'Memory Pieces': 'Mảnh ký ức',
  'No bookings yet.': 'Chưa có đặt chỗ nào.',
  'Continue exploring': 'Tiếp tục khám phá',
  'My Rewards': 'Phần thưởng của tôi',
  'My Reviews': 'Đánh giá của tôi',
  'A memory worth keeping.': 'Một ký ức đáng lưu giữ.',
  'Your Reviews': 'Đánh giá của bạn',
  'You have collected': 'Bạn đã thu thập',
  'stamp': 'con dấu',
  'stamps': 'con dấu',
  'Cultural Journey Badge': 'Huy hiệu hành trình văn hóa',
  'Discount Voucher': 'Phiếu giảm giá',
  'Premium Cultural Souvenir': 'Quà lưu niệm văn hóa cao cấp',
  'Milestone unlocked in this prototype.': 'Cột mốc đã được mở khóa trong bản mẫu này.',
  'Collect more stamps to unlock this milestone.': 'Thu thập thêm con dấu để mở khóa cột mốc này.',
  'A lovely idea.': 'Một ý tưởng thật hay.',
  'Need inspiration?': 'Cần cảm hứng?',
  'Trip Designer · Prototype': 'Thiết kế chuyến đi · Bản mẫu',
  'I love traditional crafts...': 'Tôi yêu các nghề thủ công truyền thống...',
  'Send message': 'Gửi tin nhắn',
  'I have half a day.': 'Tôi có nửa ngày.',
  'I’m traveling with my family.': 'Tôi đi cùng gia đình.',
  'I love traditional crafts.': 'Tôi yêu nghề thủ công truyền thống.',
  'I want to discover childhood culture.': 'Tôi muốn khám phá văn hóa tuổi thơ.',
  'Your suggested itinerary': 'Lịch trình gợi ý cho bạn',
  'Stop': 'Điểm dừng',
  'Explore': 'Khám phá',
  'Suggestions are generated from local sample journeys, not a live AI service.': 'Gợi ý được tạo từ các hành trình mẫu cục bộ, không phải dịch vụ AI trực tiếp.',
  'After the experience': 'Sau trải nghiệm',
  'Memory Sharing Station': 'Trạm chia sẻ ký ức',
  'Question': 'Câu hỏi',
  'of 3': 'trên 3',
  'What did you experience?': 'Bạn đã trải nghiệm điều gì?',
  'I used the bamboo pole to retrieve a lantern.': 'Tôi đã tự tay dùng sào tre rút lồng đèn',
  'I found the clay piggy bank.': 'Tôi đã tìm heo đất',
  'I followed the clue to find a to he figure.': 'Tôi đã tìm tò he theo manh mối',
  'I followed the clue.': 'Tôi đã đi theo manh mối.',
  'I talked with the artisan.': 'Tôi đã trò chuyện với nghệ nhân.',
  'I explored the station.': 'Tôi đã khám phá trạm.',
  'How did you feel?': 'Bạn cảm thấy thế nào?',
  'Rate': 'Đánh giá',
  'Tell us about your experience...': 'Hãy kể cho chúng tôi về trải nghiệm của bạn...',
  'Your experience': 'Trải nghiệm của bạn',
  'Would you come back to conquer the next station?': 'Bạn có quay lại để chinh phục trạm tiếp theo không?',
  "Definitely — I'm ready for the next station.": 'Chắc chắn rồi! Lên đường sang trạm tiếp theo ngay đây.',
  "I'm a little tired, but excited to see what the next station has in store.": 'Hơi mệt chút nhưng rất háo hức muốn xem trạm kế tiếp có gì.',
  "I'll invite my closest friends and come back to conquer the next station.": 'Từ từ để tôi rủ thêm cạ cứng cùng đi chinh phục trạm sau.',
  'Next question': 'Câu hỏi tiếp theo',
  'Collect memory piece': 'Thu thập mảnh ký ức',
  'Back': 'Quay lại',
  'Search for the Old Light': 'Tìm kiếm ánh sáng xưa',
  'Search for a Piece of Childhood Color': 'Tìm kiếm sắc màu tuổi thơ',
  'Search for the Colors of Rice Flour': 'Tìm kiếm sắc màu bột gạo',
  'Locate the Alley': 'Tìm con hẻm',
  'Follow the Sound': 'Đi theo âm thanh',
  'Find the Traditional Corner': 'Tìm góc truyền thống',
  'Decode the Hanging Rack': 'Giải mã giá treo',
  'Find the Missing Piece': 'Tìm mảnh ghép còn thiếu',
  'Find the Hidden Character': 'Tìm nhân vật ẩn',
  'Retrieve the Lantern': 'Lấy chiếc đèn lồng',
  'Receive & Decorate': 'Nhận và trang trí',
  'Touch the Flour': 'Chạm vào bột',
  'Decode the Missing Piece': 'Giải mã mảnh ghép khuyết',
  'Receive & Add Color': 'Nhận bàn giao và tô điểm',
  'Find the Street Basket': 'Tìm gánh hàng rong',
  'Touch the Dough': 'Chạm tay vào bột',
  'Phú Bình Lantern Village': 'Làng đèn lồng Phú Bình',
  'Tân Khánh Piggy Bank Village': 'Làng heo đất Tân Khánh',
  'CLAY Tò He': 'Tò he đất nặn',
  'Tân Khánh Piggy Bank Village · Nguyễn Văn Nhàn Workshop': 'Xóm Lò Nung Heo Đất Tân Khánh · Xưởng ông Nguyễn Văn Nhàn',
  'Tò He Clay · Making Point & Street Vendor Basket': 'Điểm Làm & Gánh Tò He',
  'Memories of light beneath the full moon.': 'Ký ức ánh sáng dưới trăng rằm.',
  'The sound of clay and childhood savings.': 'Âm thanh của đất và những khoản tiết kiệm tuổi thơ.',
  'The first toys shaped from flour and natural colors.': 'Những món đồ chơi đầu tiên được nặn từ bột và màu tự nhiên.',
  'Follow the clatter of clay and bring a childhood color back to life.': 'Lần theo tiếng đất và đánh thức một mảng màu tuổi thơ.',
  'Follow the scent of rice flour to a pocket-sized folk character.': 'Dò theo mùi bột gạo đến một nhân vật dân gian nhỏ xinh.',
  '2 hours': '2 giờ',
  '2.5 hours': '2,5 giờ',
  '1.5 hours': '1,5 giờ',
  'Hồ Chí Minh City': 'Thành phố Hồ Chí Minh',
  'Nguyễn Văn Nhàn, a Tân Khánh clay artisan': 'Nghệ nhân đất Tân Khánh Nguyễn Văn Nhàn',
  'The lantern makers of Phú Bình': 'Những người làm đèn lồng Phú Bình',
  'The clay artisans of Tân Khánh': 'Những nghệ nhân đất sét Tân Khánh',
  'The tò he makers': 'Những người làm tò he',
  'The page you\'re looking for doesn\'t exist or has been moved.': 'Trang bạn tìm không tồn tại hoặc đã được chuyển đi.',
  'Phiêu Việt home': 'Trang chủ Phiêu Việt',
  'Main navigation': 'Điều hướng chính',
  'Switch to English': 'Chuyển sang tiếng Anh',
  'Close menu': 'Đóng menu',
  'Open menu': 'Mở menu',
  'Mobile navigation': 'Điều hướng di động',
  'Rediscover memories in the places where they were made.': 'Tìm lại ký ức tại chính nơi chúng được tạo nên.',
  'Crafted for the stories that stay with us.': 'Dành cho những câu chuyện còn mãi.',
  'Lantern craft village': 'Làng nghề đèn lồng',
  'Our reason for wandering': 'Lý do chúng ta lên đường',
  'The stories we keep are the stories we live.': 'Những câu chuyện ta gìn giữ là những câu chuyện ta sống cùng.',
  "Phiêu Việt was created to bridge the gap between rich local cultural resources and young customers' need for active, interactive experiences. Many valuable cultural experiences remain scattered, requiring users to search for and connect the information themselves; meanwhile, some artisan activities and local organizations still lack suitable channels to reach customers.": 'Phiêu Việt được xây dựng nhằm giải quyết khoảng trống giữa nguồn tài nguyên văn hóa địa phương phong phú và nhu cầu trải nghiệm chủ động, tương tác của khách hàng trẻ. Nhiều trải nghiệm văn hóa có giá trị nhưng còn phân tán, khiến người dùng phải tự tìm kiếm và kết nối thông tin; trong khi đó, một số hoạt động của nghệ nhân và đơn vị địa phương chưa có thêm nhiều kênh tiếp cận khách hàng phù hợp.',
  "For this reason, Phiêu Việt is not intended to own destinations or organize every part of a trip. Instead, it connects and designs experiences by bringing local partners' cultural discovery points and activities together into themed journeys, combining interactive challenges with Việt Ký to record each user's exploration. This turns each individual experience into a connected cultural journey that can continue and unfold over time.": 'Từ khoảng trống này, Phiêu Việt không định hướng trở thành đơn vị sở hữu điểm đến hay tổ chức toàn bộ hoạt động du lịch, mà đóng vai trò kết nối và thiết kế trải nghiệm. Dự án tập hợp các điểm khám phá và hoạt động văn hóa từ đối tác địa phương thành những hành trình có chủ đề, kết hợp thử thách tương tác và Việt Ký để ghi nhận quá trình khám phá của người dùng. Qua đó, mỗi trải nghiệm riêng lẻ có thể trở thành một phần của hành trình văn hóa có tính liên kết và tiếp nối.',
  'Follow a lantern into a village workshop. Shape a keepsake from clay. Discover a tiny figure made from rice flour. Along the way, stories become experiences, and experiences become memories you can carry.': 'Theo ánh đèn vào xưởng làng nghề. Tạo một món quà từ đất sét. Khám phá hình hài nhỏ làm từ bột gạo. Trên hành trình ấy, câu chuyện trở thành trải nghiệm và trải nghiệm trở thành ký ức bạn có thể mang theo.',
  'Content overview': 'Tổng quan nội dung',
  'Prototype overview of the Phiêu Việt stories, stations, and journey activity.': 'Tổng quan bản mẫu về câu chuyện, trạm và hoạt động hành trình của Phiêu Việt.',
  'This page shows sample content and activity saved on this device. It is not a protected administration system.': 'Trang này hiển thị nội dung mẫu và hoạt động được lưu trên thiết bị. Đây không phải hệ thống quản trị được bảo vệ.',
  'Reviews': 'Đánh giá',
  'Destinations & stories': 'Điểm đến và câu chuyện',
  'Category': 'Danh mục',
  'Story': 'Câu chuyện',
  'Publishing, editing, uploads, and access control require a connected content service and are not enabled in this prototype.': 'Xuất bản, chỉnh sửa, tải lên và kiểm soát quyền truy cập cần dịch vụ nội dung được kết nối và chưa được bật trong bản mẫu này.',
  'an experience': 'một trải nghiệm',
  'Payment is not collected in this prototype.': 'Bản mẫu này không thu tiền thanh toán.',
  'Continue to payment': 'Tiếp tục thanh toán',
  'Your booking is confirmed.': 'Đặt chỗ của bạn đã được xác nhận.',
  'Station challenge': 'Thử thách tại trạm',
  'Follow the clues, meet the artisan, and create a new memory.': 'Theo manh mối, gặp nghệ nhân và tạo nên một ký ức mới.',
  'A three-part real-world activity': 'Hoạt động thực tế gồm ba phần',
  'Step': 'Bước',
  'Mark activity complete': 'Đánh dấu hoàn thành hoạt động',
  'Continue to next clue': 'Tiếp tục đến manh mối tiếp theo',
  'Activity complete · Memory Gift': 'Hoạt động hoàn tất · Quà ký ức',
  'Share this memory': 'Chia sẻ ký ức này',
  'Previous step': 'Bước trước',
  'Challenge unavailable.': 'Thử thách không khả dụng.',
  'Find a cultural itinerary inspired by your time and interests.': 'Tìm lịch trình văn hóa dựa trên thời gian và sở thích của bạn.',
  'Design Your Journey': 'Thiết kế hành trình của bạn',
  'Tell us how you want to experience Vietnam. We’ll sketch a cultural route around you.': 'Hãy cho chúng tôi biết bạn muốn trải nghiệm Việt Nam như thế nào. Chúng tôi sẽ phác thảo một tuyến văn hóa dành riêng cho bạn.',
  'Explore craft villages and authentic cultural experiences across Vietnam.': 'Khám phá các làng nghề và trải nghiệm văn hóa chân thực khắp Việt Nam.',
  'Craft Villages': 'Làng nghề',
  'Historical Sites': 'Di tích lịch sử',
  'Museums': 'Bảo tàng',
  'Cultural Experiences': 'Trải nghiệm văn hóa',
  'Search destinations': 'Tìm kiếm điểm đến',
  'experiences to explore': 'trải nghiệm để khám phá',
  '2 hours or more': 'Từ 2 giờ trở lên',
  'Featured': 'Nổi bật',
  'No experiences found': 'Không tìm thấy trải nghiệm',
  'Try adjusting your search or filters.': 'Hãy thử điều chỉnh tìm kiếm hoặc bộ lọc.',
  'Cultural journeys': 'Hành trình văn hóa',
  'Rediscover memories and reconnect with authentic Vietnamese heritage through stories, craft villages, and cultural experiences.': 'Tìm lại ký ức và kết nối với di sản Việt Nam nguyên bản qua những câu chuyện, làng nghề và trải nghiệm văn hóa.',
  'Lanterns and an artisan at a Vietnamese craft village': 'Đèn lồng và nghệ nhân tại một làng nghề Việt Nam',
  '01 / 03 · Light · Earth · Flour': '01 / 03 · Ánh sáng · Đất · Bột gạo',
  'Find the places and stories that call to you.': 'Tìm những nơi chốn và câu chuyện gọi tên bạn.',
  'Read & book': 'Đọc và đặt chỗ',
  'Get to know the craft, then reserve your place.': 'Tìm hiểu nghề thủ công, rồi đặt chỗ của bạn.',
  'Visit & unlock': 'Đến thăm và mở khóa',
  'Follow the clues at the destination and reveal more.': 'Theo manh mối tại điểm đến và khám phá thêm.',
  'Keep the memory': 'Lưu giữ ký ức',
  'Collect a piece of the journey in your Việt Ký.': 'Lưu một phần hành trình vào Việt Ký của bạn.',
  'Every place leaves a little piece of itself with you.': 'Mỗi nơi chốn đều để lại một phần nhỏ trong bạn.',
  "Collect memory pieces and digital stamps as you explore. Your Việt Ký is a living record of where you've been and what you've felt.": 'Thu thập mảnh ký ức và con dấu số khi bạn khám phá. Việt Ký là ghi chép sống động về nơi bạn đã đến và điều bạn đã cảm nhận.',
  'Cultural passport · No. 001': 'Hộ chiếu văn hóa · Số 001',
  'Your cultural journey': 'Hành trình văn hóa của bạn',
  'The stories you take with you': 'Những câu chuyện bạn mang theo',
  'Tell us what you love. We’ll sketch a cultural journey just for you.': 'Hãy kể chúng tôi nghe điều bạn yêu thích. Chúng tôi sẽ phác thảo một hành trình văn hóa dành riêng cho bạn.',
  'Lantern artisan at work': 'Nghệ nhân đèn lồng đang làm việc',
  'At every stop, a local artisan welcomes you into a craft passed through generations. More than an activity, it is a chance to listen, learn, and make something worth keeping.': 'Ở mỗi điểm dừng, một nghệ nhân địa phương sẽ chào đón bạn đến với nghề thủ công truyền qua nhiều thế hệ. Hơn cả một hoạt động, đây là cơ hội để lắng nghe, học hỏi và tạo ra điều đáng lưu giữ.',
  '“The loveliest part was sitting with the maker and hearing how a simple lantern carried so many memories.”': '“Điều đáng yêu nhất là được ngồi bên người thợ và nghe cách một chiếc đèn lồng giản dị mang theo biết bao ký ức.”',
  'A journey worth remembering': 'Một hành trình đáng nhớ',
  'Your story is still unfolding': 'Câu chuyện của bạn vẫn đang tiếp diễn',
  'Step beyond the screen. Meet the people, places, crafts and stories that make Vietnamese heritage unforgettable.': 'Bước ra khỏi màn hình. Gặp gỡ những con người, nơi chốn, nghề thủ công và câu chuyện làm nên di sản Việt Nam khó quên.',
  'Light, Earth, Flour journey': 'Hành trình Ánh sáng, Đất, Bột gạo',
  'Follow a three-stop cultural journey through lanterns, clay keepsakes, and tò he.': 'Theo hành trình văn hóa ba điểm dừng qua đèn lồng, món quà đất sét và tò he.',
  'The signature journey': 'Hành trình đặc trưng',
  'Three traditional crafts. Three pieces of childhood. One journey to remember.': 'Ba nghề thủ công truyền thống. Ba mảnh ghép tuổi thơ. Một hành trình đáng nhớ.',
  'Explore story': 'Khám phá câu chuyện',
  'Begin with the story that calls to you.': 'Bắt đầu từ câu chuyện gọi tên bạn.',
  'Explore experiences': 'Khám phá trải nghiệm',
  'Partner portal': 'Cổng đối tác',
  'Prototype partner overview for visits, bookings, and experience quality.': 'Tổng quan bản mẫu dành cho đối tác về lượt thăm, đặt chỗ và chất lượng trải nghiệm.',
  'Phiêu Việt · Partner workspace': 'Phiêu Việt · Không gian đối tác',
  'Partner Dashboard': 'Bảng điều khiển đối tác',
  'Prototype figures based on bookings saved on this device; not a live partner account.': 'Số liệu bản mẫu dựa trên đặt chỗ được lưu trên thiết bị này; không phải tài khoản đối tác trực tiếp.',
  'Completed experiences': 'Trải nghiệm đã hoàn thành',
  'Gross booking value': 'Tổng giá trị đặt chỗ',
  'Verify booking': 'Xác minh đặt chỗ',
  'Enter a prototype booking ID from a digital ticket.': 'Nhập mã đặt chỗ bản mẫu từ vé điện tử.',
  'Look up': 'Tra cứu',
  'Commission': 'Hoa hồng',
  'Verify': 'Xác minh',
  'Booking verified': 'Đặt chỗ đã được xác minh',
  'No booking found for this ID.': 'Không tìm thấy đặt chỗ với mã này.',
  'Your profile': 'Hồ sơ của bạn',
  'See your bookings, stamps, and memories in one place.': 'Xem đặt chỗ, con dấu và ký ức của bạn ở một nơi.',
  'Việt Ký digital passport': 'Hộ chiếu số Việt Ký',
  'Collect memory pieces and stamps from every stop of your cultural journey.': 'Thu thập mảnh ký ức và con dấu tại mỗi điểm dừng trong hành trình văn hóa.',
  'Your cultural journey, one memory at a time.': 'Hành trình văn hóa của bạn, từng ký ức một.',
  'Destinations completed': 'Điểm đến đã hoàn thành',
  'Collected along the way': 'Thu thập trên hành trình',
  'A memory still waiting to be found.': 'Một ký ức vẫn đang chờ được tìm thấy.',
  'Digital stamp collected': 'Đã thu thập con dấu số',
  'Unlock story': 'Mở khóa câu chuyện',
  'Memory sharing station': 'Trạm chia sẻ ký ức',
  'Reflect on your cultural experience and collect a memory piece.': 'Nhìn lại trải nghiệm văn hóa và thu thập một mảnh ký ức.',
  'Your rewards': 'Phần thưởng của bạn',
  'See the cultural rewards and milestones in your Phiêu Việt journey.': 'Xem phần thưởng văn hóa và các cột mốc trong hành trình Phiêu Việt của bạn.',
  'Read the memories and ratings you shared after each experience.': 'Đọc những ký ức và đánh giá bạn đã chia sẻ sau mỗi trải nghiệm.',
  'Stories of childhood': 'Những câu chuyện tuổi thơ',
  'Read the stories behind light, earth, and flour in the living craft villages of Vietnam.': 'Đọc những câu chuyện phía sau ánh sáng, đất và bột gạo tại các làng nghề sống động của Việt Nam.',
  'Preview narration': 'Nghe thử lời kể',
  'Meet ${artisan} and try the craft yourself.': 'Gặp ${artisan} và tự mình thử nghề thủ công.',
  'Digital Memory Ticket': 'Vé Ký ức số',
  'Your Phiêu Việt cultural experience ticket and journey details.': 'Vé trải nghiệm văn hóa Phiêu Việt và thông tin hành trình của bạn.',
  'A new memory begins': 'Một ký ức mới bắt đầu',
  'Your digital memory ticket': 'Vé ký ức số của bạn',
  'Your prototype reservation has been saved on this device.': 'Đặt chỗ bản mẫu của bạn đã được lưu trên thiết bị này.',
  'Digital Experience Ticket': 'Vé trải nghiệm số',
  'This ticket and QR symbol are a prototype and are not valid for admission or venue verification.': 'Vé và mã QR này chỉ là bản mẫu, không có giá trị để vào cửa hoặc xác minh tại địa điểm.',
  'Continue the journey': 'Tiếp tục hành trình',
  'Begin station challenge': 'Bắt đầu thử thách tại trạm',
  'Guests': 'Khách tham gia',
  'Show this ticket at the station.': 'Xuất trình vé này tại trạm.',
  'Back to your profile': 'Quay lại hồ sơ',
  'Unlock your story': 'Mở khóa câu chuyện của bạn',
  'Explore the simulated QR and location verification journey.': 'Khám phá hành trình mô phỏng quét QR và xác minh vị trí.',
  'You are exploring:': 'Bạn đang khám phá:',
  'Find the next chapter': 'Tìm chương tiếp theo',
  'This prototype simulates scanning a station QR code. It does not use your camera.': 'Bản mẫu này mô phỏng việc quét mã QR tại trạm. Ứng dụng không sử dụng camera của bạn.',
  'QR Code Verified (simulation)': 'Mã QR đã xác minh (mô phỏng)',
  'Location verification': 'Xác minh vị trí',
  'Choose a simulated result to preview the on-site experience. No location access is requested.': 'Chọn kết quả mô phỏng để xem trước trải nghiệm tại chỗ. Ứng dụng không yêu cầu quyền truy cập vị trí.',
  'Simulate at destination': 'Mô phỏng tại điểm đến',
  'Simulate outside area': 'Mô phỏng ngoài khu vực',
  'Location verified': 'Vị trí đã được xác minh',
  'Your story is now unlocked.': 'Câu chuyện của bạn đã được mở khóa.',
  'Continue to story': 'Tiếp tục đến câu chuyện',
  'Already unlocked': 'Đã mở khóa',
  'LIGHT': 'ÁNH SÁNG',
  'EARTH': 'ĐẤT',
  'FLOUR': 'BỘT GẠO',
  'Follow the clues to locate the artisan\'s home.': 'Theo manh mối để tìm nhà của nghệ nhân.',
  'Find the lantern marked with a five-pointed star and the shortest red ribbon.': 'Tìm chiếc đèn lồng có ngôi sao năm cánh và dải ruy băng đỏ ngắn nhất.',
  'Use the bamboo pole to carefully retrieve the lantern you discovered.': 'Dùng sào tre để cẩn thận lấy chiếc đèn lồng bạn đã tìm thấy.',
  'Long before the streets glowed with electric light, a lantern was enough to turn an evening into a celebration. In Phú Bình, skilled hands still bend bamboo into delicate frames and stretch vibrant paper across them. The craft carries the anticipation of a childhood Mid-Autumn Festival: the rustle of paper, the warmth of a candle, and the joy of walking beneath the moon.': 'Từ rất lâu trước khi đường phố rực sáng bởi đèn điện, một chiếc đèn lồng đã đủ biến buổi tối thành lễ hội. Ở Phú Bình, những đôi tay khéo léo vẫn uốn tre thành khung mảnh và căng giấy rực rỡ lên đó. Nghề thủ công mang theo niềm mong đợi của Tết Trung thu tuổi thơ: tiếng giấy xào xạc, hơi ấm ngọn nến và niềm vui bước đi dưới ánh trăng.',
  'In the quiet of the workshop, each artisan has a story that no photograph can quite capture. Come closer, follow the lantern trail, and discover the chapter waiting at the village.': 'Trong sự tĩnh lặng của xưởng nghề, mỗi nghệ nhân đều có một câu chuyện mà không bức ảnh nào có thể ghi lại trọn vẹn. Hãy đến gần hơn, theo dấu đèn lồng và khám phá chương chuyện đang chờ ở ngôi làng.',
  'A small clay piggy bank once held a world of possibilities. At Tân Khánh, artisans shape earth into the familiar childhood companion, then add color and character by hand. Every piece begins as a lump of clay and ends as a vessel for hopes, plans, and little treasures.': 'Tại xóm lò nung heo đất Tân Khánh, chú heo đất quen thuộc trở thành một mảnh ký ức tuổi thơ. Trong xưởng thủ công 30 năm tuổi của nghệ nhân Nguyễn Văn Nhàn, tiếng gõ lạch cạch của khuôn và dụng cụ dẫn lối người chơi đến bàn làm việc, nơi những chú heo đất mộc đang chờ hoàn thiện. Trải nghiệm khép lại bằng dấu ấn riêng: chọn một màu và tô điểm câu chuyện nhỏ lên món quà mang về.',
  'There is more to this craft than meets the eye. Listen for the workshop sounds and find the piece that tells your own story.': 'Mảng màu còn thiếu đang chờ đâu đó trong xưởng. Hãy lắng nghe thật kỹ, tìm trên các kệ và xin phép nghệ nhân trước khi đặt nét cuối cùng lên chú heo đất của bạn.',
  'Follow the clatter of molds and hand tools through the 30-year-old workshop until you reach the artisan\'s worktable.': 'Lần theo tiếng gõ lạch cạch của khuôn và dụng cụ qua xưởng thủ công 30 năm tuổi để tìm đến bàn làm việc của nghệ nhân.',
  'Find the special clay piggy bank described by the app, such as the limited-edition pig holding a gold bar or the pig on the innermost corner shelf.': 'Tìm chú heo đất đặc biệt theo yêu cầu trên ứng dụng, chẳng hạn chú heo đang ôm thỏi vàng phiên bản giới hạn hoặc chú heo nằm ở kệ góc trong cùng của xưởng.',
  'Ask the artisan for a brush, choose your color, and paint the missing detail on your clay piggy bank.': 'Xin phép nghệ nhân để nhận cọ, chọn màu và tự tay tô điểm chi tiết còn thiếu trên chú heo đất.',
  'Before a toy came from a box, it could come from a pair of hands. Tò he figures made from rice flour and natural colors bring folk tales and childhood imaginings to life. A little twist, a careful pinch, and a playful character appears.': 'Tò he biến bột gạo, bột nếp và màu tự nhiên thành những nhân vật nhỏ mang theo hơi ấm của trò chơi dân gian Việt Nam. Tại điểm làm và không gian gánh hàng trưng bày trên QL1A, người chơi lần theo mùi bột mới để tìm đến giỏ tò he, rồi học cách xoay, vê và nắn để một nhân vật hiện lên.',
  'The most memorable part is not choosing a figure. It is learning to shape one for yourself beside the hands that have kept this tradition alive.': 'Điều đáng nhớ nhất không chỉ là chọn một hình tò he. Đó là được học cách tự nặn một chi tiết bên cạnh đôi tay của nghệ nhân, rồi mang ký ức ấy về nhà.',
  'Follow the scent of rice flour and glutinous rice flour to the tò he display and traditional craft corner along QL1A.': 'Dò theo mùi thơm của bột gạo và bột nếp để tìm không gian trưng bày tò he và góc truyền nghề trên QL1A.',
  'Find the exact tò he character requested by the app, such as Sun Wukong holding the Ruyi Jingu Bang hidden among the figures in the bamboo basket.': 'Tìm đúng con vật hoặc nhân vật tò he theo yêu cầu trên ứng dụng, chẳng hạn Tôn Ngộ Không cầm Như Ý Kim Cô Bổng ẩn giữa các hình trong giỏ tre.',
  'With the artisan\'s guidance, knead and shape one small detail, or receive the found figure as a keepsake.': 'Sau khi tìm đúng mục tiêu, hãy để nghệ nhân hướng dẫn bạn nhào nặn một chi tiết nhỏ hoặc nhận trực tiếp tác phẩm ấy làm kỷ niệm.',
  'Station ${number} · ${theme}': 'Trạm ${number} · ${theme}',
  'From ${formatted price}': 'Từ ${formatted price}',
  'A lantern glowing in the night. The first coins in a clay piggy bank. A tiny figure shaped by hand. Phiêu Việt takes you beyond the screen and into the workshops, stories, and people keeping childhood traditions alive.': 'Một chiếc đèn lồng tỏa sáng trong đêm. Những đồng tiền đầu tiên trong chú heo đất. Một hình hài nhỏ được nặn bằng tay. Phiêu Việt đưa bạn vượt ra ngoài màn hình để bước vào những xưởng nghề, câu chuyện và con người đang gìn giữ truyền thống tuổi thơ.',
};

const reverseTranslations = Object.fromEntries(Object.entries(translations).map(([english, vietnamese]) => [vietnamese, english]));

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
};

const Context = createContext<LanguageContextValue | null>(null);
const storageKey = 'phieu-viet-language-v1';

function loadLanguage(): Language {
  if (typeof window === 'undefined') return 'vi';
  return localStorage.getItem(storageKey) === 'en' ? 'en' : 'vi';
}

function translateDocument(language: Language) {
  if (typeof document === 'undefined') return;
  const dictionary = language === 'vi' ? translations : reverseTranslations;
  const keys = Object.keys(dictionary).sort((left, right) => right.length - left.length);
  const replaceText = (value: string) => keys.reduce((text, key) => text.split(key).join(dictionary[key]), value);
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
  const textNodes: Text[] = [];
  let node = walker.nextNode();
  while (node) {
    if (node.parentElement && !['SCRIPT', 'STYLE'].includes(node.parentElement.tagName)) textNodes.push(node as Text);
    node = walker.nextNode();
  }
  textNodes.forEach((textNode) => {
    const nextText = replaceText(textNode.nodeValue || '');
    if (nextText !== textNode.nodeValue) textNode.nodeValue = nextText;
  });
  document.querySelectorAll<HTMLElement>('[aria-label], [placeholder], [title]').forEach((element) => {
    ['aria-label', 'placeholder', 'title'].forEach((attribute) => {
      const value = element.getAttribute(attribute);
      if (value) element.setAttribute(attribute, replaceText(value));
    });
  });
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('vi');

  useEffect(() => {
    const frame = window.requestAnimationFrame(() => {
      const initialLanguage = loadLanguage();
      setLanguage(initialLanguage);
      document.documentElement.lang = initialLanguage;
    });
    return () => window.cancelAnimationFrame(frame);
  }, []);

  useEffect(() => {
    let observer: MutationObserver | undefined;
    const frame = window.requestAnimationFrame(() => {
      translateDocument(language);
      observer = new MutationObserver(() => {
        observer?.disconnect();
        translateDocument(language);
        observer?.observe(document.body, { childList: true, subtree: true });
      });
      observer.observe(document.body, { childList: true, subtree: true });
    });
    return () => {
      window.cancelAnimationFrame(frame);
      observer?.disconnect();
    };
  }, [language]);

  function changeLanguage(nextLanguage: Language) {
    setLanguage(nextLanguage);
    localStorage.setItem(storageKey, nextLanguage);
    document.documentElement.lang = nextLanguage;
  }

  function toggleLanguage() {
    changeLanguage(language === 'vi' ? 'en' : 'vi');
  }

  return <Context.Provider value={{ language, setLanguage: changeLanguage, toggleLanguage }}>{children}</Context.Provider>;
}

export function useLanguage() {
  const value = useContext(Context);
  if (!value) throw new Error('LanguageProvider missing');
  return value;
}
