/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as JourneysRouteImport } from './routes/journeys'
import { Route as StoriesIndexRouteImport } from './routes/stories.index'
import { Route as StoriesStationIdRouteImport } from './routes/stories.$stationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysRoute = JourneysRouteImport.update({
  id: '/journeys',
  path: '/journeys',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesStationIdRoute = StoriesStationIdRouteImport.update({
  id: '/stories/$stationId',
  path: '/stories/$stationId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/journeys': typeof JourneysRoute
  '/stories/$stationId': typeof StoriesStationIdRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/journeys': typeof JourneysRoute
  '/stories/$stationId': typeof StoriesStationIdRoute
  '/stories': typeof StoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/journeys': typeof JourneysRoute
  '/stories/$stationId': typeof StoriesStationIdRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/discover' | '/journeys' | '/stories/$stationId' | '/stories/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/discover' | '/journeys' | '/stories/$stationId' | '/stories'
  id:
    | '__root__'
    | '/'
    | '/discover'
    | '/journeys'
    | '/stories/$stationId'
    | '/stories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoverRoute: typeof DiscoverRoute
  JourneysRoute: typeof JourneysRoute
  StoriesStationIdRoute: typeof StoriesStationIdRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys': {
      id: '/journeys'
      path: '/journeys'
      fullPath: '/journeys'
      preLoaderRoute: typeof JourneysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$stationId': {
      id: '/stories/$stationId'
      path: '/stories/$stationId'
      fullPath: '/stories/$stationId'
      preLoaderRoute: typeof StoriesStationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoverRoute: DiscoverRoute,
  JourneysRoute: JourneysRoute,
  StoriesStationIdRoute: StoriesStationIdRoute,
  StoriesIndexRoute: StoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
