/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as JourneysRouteImport } from './routes/journeys'
import { Route as BookStationIdRouteImport } from './routes/book.$stationId'
import { Route as ChallengeStationIdRouteImport } from './routes/challenge.$stationId'
import { Route as StoriesIndexRouteImport } from './routes/stories.index'
import { Route as StoriesStationIdRouteImport } from './routes/stories.$stationId'
import { Route as TicketBookingIdRouteImport } from './routes/ticket.$bookingId'
import { Route as UnlockStationIdRouteImport } from './routes/unlock.$stationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysRoute = JourneysRouteImport.update({
  id: '/journeys',
  path: '/journeys',
  getParentRoute: () => rootRouteImport,
} as any)
const BookStationIdRoute = BookStationIdRouteImport.update({
  id: '/book/$stationId',
  path: '/book/$stationId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeStationIdRoute = ChallengeStationIdRouteImport.update({
  id: '/challenge/$stationId',
  path: '/challenge/$stationId',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesStationIdRoute = StoriesStationIdRouteImport.update({
  id: '/stories/$stationId',
  path: '/stories/$stationId',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketBookingIdRoute = TicketBookingIdRouteImport.update({
  id: '/ticket/$bookingId',
  path: '/ticket/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockStationIdRoute = UnlockStationIdRouteImport.update({
  id: '/unlock/$stationId',
  path: '/unlock/$stationId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/journeys': typeof JourneysRoute
  '/book/$stationId': typeof BookStationIdRoute
  '/challenge/$stationId': typeof ChallengeStationIdRoute
  '/stories/$stationId': typeof StoriesStationIdRoute
  '/ticket/$bookingId': typeof TicketBookingIdRoute
  '/unlock/$stationId': typeof UnlockStationIdRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/journeys': typeof JourneysRoute
  '/book/$stationId': typeof BookStationIdRoute
  '/challenge/$stationId': typeof ChallengeStationIdRoute
  '/stories/$stationId': typeof StoriesStationIdRoute
  '/ticket/$bookingId': typeof TicketBookingIdRoute
  '/unlock/$stationId': typeof UnlockStationIdRoute
  '/stories': typeof StoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/journeys': typeof JourneysRoute
  '/book/$stationId': typeof BookStationIdRoute
  '/challenge/$stationId': typeof ChallengeStationIdRoute
  '/stories/$stationId': typeof StoriesStationIdRoute
  '/ticket/$bookingId': typeof TicketBookingIdRoute
  '/unlock/$stationId': typeof UnlockStationIdRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/journeys'
    | '/book/$stationId'
    | '/challenge/$stationId'
    | '/stories/$stationId'
    | '/ticket/$bookingId'
    | '/unlock/$stationId'
    | '/stories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/journeys'
    | '/book/$stationId'
    | '/challenge/$stationId'
    | '/stories/$stationId'
    | '/ticket/$bookingId'
    | '/unlock/$stationId'
    | '/stories'
  id:
    | '__root__'
    | '/'
    | '/discover'
    | '/journeys'
    | '/book/$stationId'
    | '/challenge/$stationId'
    | '/stories/$stationId'
    | '/ticket/$bookingId'
    | '/unlock/$stationId'
    | '/stories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoverRoute: typeof DiscoverRoute
  JourneysRoute: typeof JourneysRoute
  BookStationIdRoute: typeof BookStationIdRoute
  ChallengeStationIdRoute: typeof ChallengeStationIdRoute
  StoriesStationIdRoute: typeof StoriesStationIdRoute
  TicketBookingIdRoute: typeof TicketBookingIdRoute
  UnlockStationIdRoute: typeof UnlockStationIdRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys': {
      id: '/journeys'
      path: '/journeys'
      fullPath: '/journeys'
      preLoaderRoute: typeof JourneysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$stationId': {
      id: '/book/$stationId'
      path: '/book/$stationId'
      fullPath: '/book/$stationId'
      preLoaderRoute: typeof BookStationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge/$stationId': {
      id: '/challenge/$stationId'
      path: '/challenge/$stationId'
      fullPath: '/challenge/$stationId'
      preLoaderRoute: typeof ChallengeStationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$stationId': {
      id: '/stories/$stationId'
      path: '/stories/$stationId'
      fullPath: '/stories/$stationId'
      preLoaderRoute: typeof StoriesStationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$bookingId': {
      id: '/ticket/$bookingId'
      path: '/ticket/$bookingId'
      fullPath: '/ticket/$bookingId'
      preLoaderRoute: typeof TicketBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock/$stationId': {
      id: '/unlock/$stationId'
      path: '/unlock/$stationId'
      fullPath: '/unlock/$stationId'
      preLoaderRoute: typeof UnlockStationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoverRoute: DiscoverRoute,
  JourneysRoute: JourneysRoute,
  BookStationIdRoute: BookStationIdRoute,
  ChallengeStationIdRoute: ChallengeStationIdRoute,
  StoriesStationIdRoute: StoriesStationIdRoute,
  TicketBookingIdRoute: TicketBookingIdRoute,
  UnlockStationIdRoute: UnlockStationIdRoute,
  StoriesIndexRoute: StoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
